FlowCrypt/flowcrypt-ios

- FlowCrypt/Controllers/Compose/ComposeViewController.swift
- FlowCrypt/Controllers/Setup/SetupViewController.swift
- FlowCrypt/Functionality/Services/Google/GoogleService.swift
- FlowCryptUITests/SignInTest.swift
- Makefile
> Temporary disable search contacts

- FlowCrypt.xcodeproj/project.pbxproj
- FlowCrypt/Extensions/PromiseKitExtension.swift
- FlowCrypt/Functionality/Services/AttesterApi.swift
- FlowCrypt/Functionality/Services/WKDURLsApi.swift
- FlowCrypt/Functionality/WKDURLs/PubLookup.swift
- FlowCrypt/Functionality/WKDURLs/WKDURLsConstructor.swift
- FlowCryptTests/Functionallity/WKDURLs/WKDURLsConstructorTests.swift
This PR implements logic for retrieving wkd or attester public keys;
issue #296
**Tests**:
- Tests updated for WKDURLsConstructor
- Can't add tests for WKDURLsApi and AttesterApi because there is no networking entity that injects into these classes and could be spied. 
P.S. It would be great to refactor Networking call `URLSession.shared.call(_ urlRequest: URLRequest, tolerateStatus: [Int]? = nil) -> Promise<HttpRes>` for separate networking entity to test classes that make API calls.
> WKD public keys - for now not integrated

- FlowCrypt.xcodeproj/project.pbxproj
- FlowCrypt/App/Configuration.swift
- FlowCrypt/Core/Core.swift
- FlowCrypt/Functionality/Services/EnterpriseServerApi.swift
- FlowCrypt/Functionality/Services/WKDURLsApi.swift
- FlowCryptCommon/Extensions/CodableExntensions.swift
- FlowCryptCommon/Extensions/Data/DataExtensions.swift
This PR adds service to retrieve FES url configuration
issue #339
**Tests** :
- Difficult to test because we have no separate layer for networking that could be "spied"
> Prepwork for retrieving client config from FES

- FlowCrypt/Controllers/Inbox/InboxViewController.swift
- FlowCrypt/Functionality/Services/EnterpriseServerApi.swift
This PR implements checking FES on auth
close #339 
**Tests**:
- Difficult to test
> Check FES when loading inbox

- FlowCrypt/Common UI/CommonNodesInputs.swift
- FlowCrypt/Resources/en.lproj/Localizable.strings
This PR changes wording for passphrase selection
close #359 
> Better wording for pass phrase selection

- FlowCrypt/Functionality/DataManager/Encrypted Storage/EncryptedStorage.swift
This PR moved removing of client config before user deletion while logging out;
close #386
**Tests**:
> Order of db deletion

- FlowCrypt.xcodeproj/project.pbxproj
- FlowCrypt/Controllers/Compose/ComposeViewController.swift
- FlowCrypt/Extensions/CombineExtensions.swift
- FlowCrypt/Functionality/Mail Provider/Message Gateway/GmailService+send.swift
- FlowCrypt/Functionality/Mail Provider/Message Gateway/Imap+send.swift
- FlowCrypt/Functionality/Mail Provider/Message Gateway/MessageGateway.swift
- FlowCrypt/Functionality/Services/Backup Services/BackupService.swift
This PR replace usage of Promises in `MessageGateway`
issue #290
- Difficult to test. Firstly need move to Combine
> Use Combine for MessageGateway

- FlowCrypt/Functionality/Mail Provider/MessagesList Provider/Model/MessageLabel.swift
- FlowCrypt/Functionality/Services/EnterpriseServerApi.swift
- FlowCrypt/Functionality/Services/GoogleUserService.swift
- FlowCrypt/Functionality/Services/Organisational Rules Service/OrganisationalRulesService.swift
This PR replaces assertion failures with fatal errors in appropriate services;
close #387
**Tests** :
> Replace assertions with fatal error - Services

- FlowCrypt.xcodeproj/project.pbxproj
- FlowCrypt/Controllers/Compose/ComposeViewController.swift
- FlowCrypt/Extensions/CombineExtensions.swift
This PR adds `sinkFuture` as an extension to `Publisher`
close #402
**Tests** _(delete all except exactly one)_: 
- Not worth testing 
> Increase succintness of Future handling in Combine

- FlowCrypt/Controllers/SetupImap/SetupImapViewController.swift
- FlowCrypt/Functionality/Mail Provider/MessagesList Provider/Model/MessageLabel.swift
- FlowCryptUITests/Resources/UserCredentials.swift
- FlowCryptUITests/SignInImapTest.swift
This PR adds UI tests described in
#486 
#481
close #485
**Tests**:
* UI Tests - Check send message functionality to user without key.
* UI Tests - Verify that we can't send message without subject and entered message.
* UI Tests - Settings and folders functionality
> Add UI Tests - no key, settings, folders, wrong creds

- Core/source/entrypoint-bare.ts
- Core/source/mobile-interface/endpoints.ts
- Core/source/mobile-interface/format-output.ts
- Core/source/test.ts
- Core/source/test/test-utils.ts
This PR changes format of the TS Core response. 
issue #508 - only the typescript part without rebuilding js and Swift
> issue #508 return core response directly instead of encoding - TypeScript parts

- FlowCrypt/Core/CoreTypes.swift
- FlowCrypt/Functionality/Pgp/KeyMethods.swift
- FlowCryptAppTests/Core/FlowCryptCoreTests.swift
- FlowCryptAppTests/Functionallity/PGP/KeyMethodsTest.swift
This PR makes `decryptedKey` property of `DecryptKey` not nullable.
close #426  // if this PR closes an issue
- Tests added or updated - deleted `testNoDecryptedKey` test (as `decryptedKey` can't be `nil` now), updated `testDecryptKeyWithWrongPassPhrase` and `testDecryptKeyWithWrongPassPhrase` tests to handle updated `decryptedKey` property
> issue #426 make decryptedKey not nullable

- FlowCrypt/Controllers/Compose/ComposeViewController.swift
This PR fixes attachment size checking on Compose view
close #550
**Tests** :
> Wrong attachment size check on compose message

- FlowCrypt/Controllers/Setup/SetupCreatePassphraseAbstractViewController.swift
- FlowCrypt/Functionality/DataManager/Encrypted Storage/KeyChainService.swift
- FlowCrypt/Functionality/Services/Key Services/PassPhraseService.swift
This PR removes sensitive information from logs. I noticed only passphrases printed to logs, please let me know if you'll notice other important information in logs.
issue #440  - edited tom, oauth ID tokens left
**Tests**:
- Does not need tests
> issue #440 stop logging sensitive information

- Core/source/entrypoint-bare.ts
- FlowCrypt/Core/Core.swift
> Use a byte array instead of b64string for Core request data

- FlowCrypt/Functionality/Services/AttesterApi.swift
- FlowCrypt/Models/OrganisationalRule.swift
- FlowCrypt/Resources/en.lproj/Localizable.strings
This PR updates canLookupThisRecipientOnAttester OrgRule, ignores attester api depending on canLookupThisRecipientOnAttester
close #299
**Tests**:
- Difficult to test
> [code ok] Disallow attester organisational rule

- .semaphore/semaphore.yml
- FlowCrypt.xcodeproj/project.pbxproj
- FlowCrypt/Controllers/Setup/PassPhraseSaveable.swift
- FlowCrypt/Controllers/Setup/SetupBackupsViewController.swift
- FlowCrypt/Controllers/Setup/SetupCreatePassphraseAbstractViewController.swift
- FlowCrypt/Controllers/Setup/SetupEKMKeyViewController.swift
- FlowCrypt/Controllers/Setup/SetupGenerateKeyViewController.swift
- FlowCrypt/Controllers/Setup/SetupManuallyEnterPassPhraseViewController.swift
- FlowCrypt/Functionality/DataManager/StorageMethod.swift
- FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift
- FlowCrypt/Functionality/Services/Key Services/PassPhraseService.swift
- FlowCryptAppTests/Functionality/Services/PassPhraseStorageTests/PassPhraseStorageTests.swift
- Podfile.lock
This PR replaces boolean values for passphrases storage with `StorageMethod` enum
close #583
**Tests**:
- Tests added or updated - updated `PassPhraseStorageTests` to use new `storageMethod` param
> issue #583 add StorageMethod enum

- FlowCrypt/Controllers/Compose/ComposeViewController.swift
- FlowCrypt/Controllers/Settings/Contacts/Contacts List/ContactsListViewController.swift
- FlowCrypt/Functionality/Services/CacheService.swift
- FlowCrypt/Functionality/Services/Contacts Services/ContactsService.swift
- FlowCrypt/Functionality/Services/Contacts Services/LocalContactsProvider.swift
- FlowCrypt/Functionality/Services/Folders Services/LocalFoldersProvider.swift
- FlowCrypt/Functionality/Services/Organisational Rules Service/ClientConfigurationProvider.swift
- FlowCrypt/Models/Realm Models/ClientConfigurationObject.swift
This PR make `UserObject` required in `ClientConfiguration `
Refactored `CacheService`
close #600
**Tests**:
- Does not need tests (refactor only)
> Make UserObject required in ClientConfiguration

- FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageAttachment.swift
- FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift
This PR adds .pgp extension to attachments right before sending them
close #538
**Tests** :
> Don't add .pgp to file list when attaching files on compose screen

- FlowCrypt/Controllers/Compose/ComposeViewController.swift
- FlowCryptCommon/Extensions/CollectionExtensions.swift
- FlowCryptUI/Nodes/AttachmentNode.swift
This PR adds remove attachment feature to compose message view
close #539
**Tests** :
> Add remove attachment feature

- FlowCrypt/Controllers/Setup/SetupBackupsViewController.swift
- FlowCrypt/Controllers/Setup/SetupCreatePassphraseAbstractViewController.swift
- FlowCrypt/Controllers/Setup/SetupEKMKeyViewController.swift
This PR changes use another account button to back button, except in `SetupManuallyEnterPassPhraseViewController` because it is root viewController of navigation stack
close #596
**Tests**:
> changed use another account button to back button

- Core/source/assets/flowcrypt-ios-begin.js
- Core/source/entrypoint-bare.ts
- FlowCrypt/Core/Core.swift
- FlowCrypt/Core/CoreHost.swift
- FlowCrypt/Functionality/Services/AppStartup.swift
- FlowCryptAppTests/Core/FlowCryptCoreTests.swift
- FlowCryptAppTests/Functionality/Services/Key Services/KeyServiceTests.swift
> Core class should be converted to actor

- FlowCrypt/Functionality/Mail Provider/Message Gateway/GmailService+draft.swift
- FlowCrypt/Functionality/Mail Provider/Message Gateway/MessageGateway.swift
- FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift
- FlowCryptAppTests/Mocks/DraftGatewayMock.swift
This PR is about removal of unused draft API
close #868 
> get draft method is unused and was removed

- FlowCrypt/Controllers/CheckAuthScopes/CheckAuthScopesViewController.swift
- FlowCrypt/Functionality/Mail Provider/Contacts Provider/CloudContactsProvider.swift
- FlowCrypt/Functionality/Services/GeneralConstants.swift
- FlowCryptAppTests/GeneralConstantsTest.swift
This PR adds search through email addresses which are not stored in user's Gmail contacts. It also needs additional auth scope `https://www.googleapis.com/auth/contacts.other.readonly` (currently it shows warning screen when user authenticates for the first time)
close #743
- Difficult to test (explain why) - it needs Google auth for testing search results.
> issue 743 contacts.other search

- FlowCrypt/Functionality/Services/Local Pub Key Services/Models/PubKey.swift
- FlowCryptAppTests/Functionality/Services/Key Services/Models/RecipientTests.swift
- FlowCryptAppTests/Mocks/KeyStorageMock.swift
This PR adds user emails to PubKey
close #812
- Tests added or updated - updated `testRecipientWithValidKey` test to check parsed `PubKey` emails.
> issue #812 add user emails to PubKey

- FlowCrypt/Controllers/Inbox/InboxRenderable.swift
- FlowCrypt/Controllers/Inbox/InboxViewController.swift
- FlowCrypt/Controllers/Inbox/InboxViewDecorator.swift
- FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
- FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift
- FlowCryptUI/Cell Nodes/InboxCellNode.swift
> PR review feedback for threads

- FlowCrypt/Controllers/Inbox/InboxProviders.swift
- FlowCrypt/Controllers/Inbox/InboxRenderable.swift
- FlowCrypt/Controllers/Inbox/InboxViewController+Factory.swift
- FlowCrypt/Controllers/Inbox/InboxViewController.swift
- FlowCrypt/Functionality/Mail Provider/Threads/MessagesThreadProvider.swift
This PR:
- close #960 - was date of first msg instead of last
- close #948 - reduced concurrency
- close #950 - just wrong ordering
- renames various vars and methods for clarity
`for try await result in taskGroup` seems to execute in order that the tasks finish, not necessarily in the order in which the `taskGroup` array was defined. Instead of using an array to collect results, using a dict by id now, which is then converted to array in expected order.
When the order is kept correct that way, `.sort()` is no longer needed on the result. The sort was broken anyway, sorting by first message in thread. 
**Tests**:
- tests will be added in https://github.com/FlowCrypt/flowcrypt-ios/issues/959
I have reviewed that this PR... …
> issues 948 950 960 fix inbox conversations data

- FlowCrypt/Controllers/Compose/ComposeViewController.swift
- FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift
- FlowCrypt/Controllers/Setup/SetupCreatePassphraseAbstractViewController.swift
- FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
- FlowCrypt/Functionality/Mail Provider/Contacts Provider/CloudContactsProvider.swift
- FlowCrypt/Functionality/Mail Provider/Message Gateway/GmailService+draft.swift
- FlowCrypt/Functionality/Mail Provider/Message Gateway/GmailService+send.swift
- FlowCrypt/Functionality/Mail Provider/Message Gateway/Imap+send.swift
- FlowCrypt/Functionality/Mail Provider/Message Provider/Gmail+Message.swift
- FlowCrypt/Functionality/Mail Provider/Message Provider/Imap+Message.swift
- FlowCrypt/Functionality/Mail Provider/MessageOperations Provider/Gmail+MessageOperations.swift
- FlowCrypt/Functionality/Mail Provider/MessageOperations Provider/Imap+MessageOperations.swift
- FlowCrypt/Functionality/Mail Provider/MessagesList Provider/Gmail+MessagesList.swift
- FlowCrypt/Functionality/Mail Provider/Threads/MessagesThreadOperationsProvider.swift
- FlowCrypt/Functionality/Mail Provider/Threads/MessagesThreadProvider.swift
This PR always adds a return before `continuation.resume` even if it's not needed there.
While it may look like an overkill, if we make this a convention, we will ensure to never run into the same bug again, and it will be easier to catch these bugs in PR reviews even without full context of the surrounding code. Missing return -> code smell, even if the code is otherwise correct.
close #966
**Tests**:
> issue 966 always return on continuation.resume

- FlowCrypt/Controllers/Compose/ComposeViewController.swift
This PR temporarily disables drafts so that we can do a release without first fixing draft-related issues.
close #975
**Tests**:
- not updating tests - drafts are not tested yet
> issue 975 temporarily disabled drafts

- appium/tests/helpers/TouchHelper.ts
- appium/tests/screenobjects/all-screens.ts
- appium/tests/screenobjects/email.screen.ts
- appium/tests/screenobjects/menu-bar.screen.ts
- appium/tests/screenobjects/sent.screen.ts
- appium/tests/screenobjects/trash.screen.ts
- appium/tests/specs/composeEmail/SendEncryptedEmailAfterWrongPassPhrase.spec.ts
This PR contains changes for SendEncryptedEmail spec , added scrollUp and scrollDown methods to TouchHelper for refreshing sent and trash lists, added checks for move sent email to trash and delete it from trash list
close #1029 
**Tests** 
> added move to trash and delete steps for SendEncryptedEmail spec

- appium/config/wdio.shared.conf.js
- appium/package.json
- appium/tests/specs/login/GmailLogin.spec.ts
This PR contains changes wdio-video-reporter - > the failed spec video will attach to artifacts
close #1052
**Tests** 
> added wdio-video-reporter for failed spec video recording

- FlowCrypt/Common UI/AttachmentManager.swift
- FlowCrypt/Common UI/Refreshable.swift
- FlowCrypt/Controllers/Compose/ComposeViewController.swift
- FlowCrypt/Controllers/Inbox/Container/InboxViewContainerController.swift
- FlowCrypt/Controllers/Inbox/InboxViewController+Factory.swift
- FlowCrypt/Controllers/Inbox/InboxViewController.swift
- FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift
- FlowCrypt/Controllers/Settings/Backup/Backups Option Scene/BackupOptionsViewController.swift
- FlowCrypt/Controllers/Settings/Backup/Backups Scene/BackupViewController.swift
- FlowCrypt/Controllers/Settings/Backup/Backups Seleckt Key Scene/BackupSelectKeyViewController.swift
- FlowCrypt/Controllers/Settings/KeySettings/Key List/KeySettingsViewController.swift
- FlowCrypt/Controllers/Setup/PassPhraseSaveable.swift
- FlowCrypt/Controllers/Setup/SetupGenerateKeyViewController.swift
- FlowCrypt/Controllers/Setup/SetupManuallyImportKeyViewController.swift
- FlowCrypt/Controllers/SetupImap/SetupImapViewController.swift
- FlowCrypt/Controllers/SideMenu/Main/SideMenuNavigationController.swift
- FlowCrypt/Controllers/SideMenu/Menu/MyMenuViewController.swift
- FlowCrypt/Controllers/SideMenu/NavigationController/NavigationChildController.swift
- FlowCrypt/Controllers/Threads/MessageActionsHandler.swift
- FlowCrypt/Extensions/UIViewController+Spinner.swift
- FlowCrypt/Extensions/UIViewControllerExtensions.swift
- FlowCrypt/Functionality/Error Handling/ErrorHandler.swift
- FlowCrypt/Functionality/Mail Provider/UsersMailSession Provider/UserMailSessionProvider.swift
- FlowCrypt/Functionality/Services/GlobalRouter.swift
- FlowCryptUI/Nodes/TableViewController.swift
> Use @MainActor instead of DispatchQueue.main.async

- appium/tests/screenobjects/inbox.screen.ts
This PR attempts to improve running tests on my device.
issue #1070
- Tests updated
> stabilize inbox screen

- FlowCrypt.xcodeproj/project.pbxproj
- FlowCrypt/Controllers/Compose/ComposeViewController.swift
- FlowCrypt/Controllers/Compose/ComposeViewControllerInput.swift
- FlowCrypt/Controllers/Compose/ComposeViewDecorator.swift
- FlowCrypt/Controllers/Inbox/InboxViewController+State.swift
- FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift
- FlowCrypt/Controllers/Threads/ThreadDetailsDecorator.swift
- FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
- FlowCrypt/Functionality/FilesManager/FilesManager.swift
- FlowCrypt/Functionality/Mail Provider/Message Provider/MessageAttachment.swift
- FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift
- FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift
- FlowCryptAppTests/Functionality/FilesManager/FileMock.swift
- FlowCryptUI/Nodes/AttachmentNode.swift
- appium/tests/screenobjects/email.screen.ts
- appium/tests/screenobjects/new-message.screen.ts
- appium/tests/specs/inbox/CheckReplyAndForwardForEncryptedEmail.spec.ts
This PR adds attachments support for forwarded messages
close #903
- Tests added or updated - updated UI test to check attachment presence
> #903 Include attachments in forwarded messages

- appium/tests/helpers/ElementHelper.ts
- appium/tests/helpers/TouchHelper.ts
- appium/tests/screenobjects/mail-folder.screen.ts
- appium/tests/specs/composeEmail/SendEncryptedEmailAfterPassPhraseSessionEndedAndTrashIt.spec.ts
- appium/tests/specs/inbox/CheckEncryptedEmailAfterRestartApp.spec.ts
- appium/tests/specs/inbox/ReadAttachmentEmail.spec.ts
- appium/tests/specs/inbox/ReadEmailAfterRestartApp.spec.ts
- appium/tests/specs/inbox/ReadKeyMismatchEmail.spec.ts
Cherry-picking a commit from PR #1103 to potentially fix tests on master sooner.
issue #1071 // if it doesn't close the issue yet
> issue 1071 appium inbox scroll improvements

- FlowCrypt.xcodeproj/project.pbxproj
- FlowCrypt/Controllers/Bootstrap/InvalidStorageViewController.swift
- FlowCrypt/Functionality/Services/GlobalRouter.swift
- FlowCrypt/Resources/UI Guidance.md
This PR rebuild `InvalidStorageViewController` with Texture. Added UI Guidance
close #766 
**Tests**:
- Does not need tests (refactor only, docs or internal changes) 
> Rebuild InvalidStorageViewController with Texture

- FlowCrypt/Functionality/Mail Provider/MessageOperations Provider/Gmail+MessageOperations.swift
- FlowCrypt/Functionality/Mail Provider/MessagesList Provider/Model/MessageLabel.swift
This PR fix removing all labels for gmail archive operation
close #816
**Tests**:
> Remove only inbox label for archive operation

- FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift
- FlowCrypt/Resources/en.lproj/Localizable.strings
- appium/tests/specs/inbox/CheckAllEmailSignatureCases.spec.ts
> Highlight mixed or partial signatures

- appium/tests/specs/inbox/CheckAllEmailSignatureCases.spec.ts
> Message signed by unknown key should have a different badge

- appium/tests/data/index.ts
- appium/tests/specs/inbox/CheckMessageProcessingErrors.spec.ts
This PR contains new test for checking message processing error
close #1095 
issue #1144 
**Tests** 
> added tests for view message processing errors

- FlowCrypt/Functionality/Services/Local Private Key Services/PassPhraseService.swift
- FlowCryptAppTests/Functionality/Services/PassPhraseStorageTests/PassPhraseStorageTests.swift
This PR improves clarity in pass phrase storage init.
close #1136
> issue 1136 clarified storage name

- appium/config/wdio.live.conf.js
- appium/tests/screenobjects/splash.screen.ts
- appium/tests/specs/live/login/CancelLoginAndLogout.spec.ts
This PR contains new spec for cancel login + login + logout, updated live config
close #1186 
**Tests**
> added new spec for cancel login + login + logout

- FlowCrypt/Controllers/Compose/ComposeViewController.swift
- FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift
- FlowCrypt/Resources/en.lproj/Localizable.strings
This PR updates sending mail alert messages (shows `Sending` instead of `Uploading 100%`) 
close #1160 
> #1160 update sent message alert

- appium/tests/screenobjects/attachment.screen.ts
- appium/tests/screenobjects/email.screen.ts
- appium/tests/specs/live/inbox/ReadAttachmentEmail.spec.ts
This PR contains changes for check email with attachment spec, added new methods, updated selectors
close #1204 
**Tests**
> added fixes for check attachment spec

- FlowCrypt.xcworkspace/xcshareddata/swiftpm/Package.resolved
- FlowCrypt/Controllers/Setup/SetupInitialViewController.swift
- FlowCrypt/Extensions/BundleExtensions.swift
- FlowCrypt/Extensions/CommandLineExtensions.swift
- FlowCrypt/Extensions/String+Extension.swift
- FlowCrypt/Extensions/UIViewController+Spinner.swift
- FlowCrypt/Functionality/DataManager/DataService.swift
- FlowCrypt/Functionality/DataManager/SessionService.swift
- FlowCrypt/Functionality/Services/GoogleUserService.swift
- FlowCrypt/Functionality/Services/Local Private Key Services/KeyService.swift
- FlowCrypt/Functionality/Services/Local Private Key Services/PassPhraseService.swift
- FlowCrypt/Functionality/Services/Remote Private Key Services/EmailKeyManagerApi.swift
- FlowCrypt/Functionality/Services/Remote Pub Key Services/AttesterApi.swift
- FlowCrypt/Resources/en.lproj/Localizable.strings
- FlowCryptAppTests/Functionality/Mail Provider/GmailServiceTest.swift
- Podfile.lock
This PR adds auto-refresh for Google id tokens.
close #1091
- Difficult to test (explain why) - it's `GTMAppAuth` built-in functionality and we're using mock `GoogleUserService` in tests.
> #1091 add google id tokens refresh

- appium/config/wdio.shared.conf.js
This PR changes report files format from `.log` to `.xml` for Semaphore compatibility.
close #1215
> #1215 Fix Semaphore test reports

- appium/tests/data/index.ts
- appium/tests/screenobjects/base.screen.ts
- appium/tests/specs/live/composeEmail/SendEmailToRecipientWithExpiredAndRevokedPublicKeys.spec.ts
- appium/tests/specs/live/composeEmail/SendEmailToRecipientWithoutPublicKey.spec.ts
- appium/tests/specs/live/composeEmail/SendEncryptedEmailAfterPassPhraseSessionEndedAndTrashIt.spec.ts
- appium/tests/specs/mock/setup/SetupFailsWithInconsistentClientConfiguration.spec.ts
- appium/tests/specs/mock/setup/SetupShowsMeaningfulErrorFromFES.spec.ts
This PR contains changes for checkErrorModal method, updated mock and live tests
close #1179 
**Tests** 
> update for checkErrorModal method

- FlowCrypt/Controllers/Settings/Backup/Backups Scene/BackupViewDecorator.swift
This PR fix text colors for backup screen
close #1014 
-----------------------------
---
> Fix text color for backup screen

- appium/config/wdio.live.conf.js
- appium/tests/data/index.ts
- appium/tests/specs/live/inbox/CheckMessageProcessingErrors.spec.ts
Added new verification for "key mismatch unexpectedly produces a modal", updated "not integrity protected - should show a warning and not decrypt automatically" message check
This PR contains new verification for "key mismatch unexpectedly produces a modal", update for "not integrity protected - should show a warning and not decrypt automatically" message 
close #1234 
**Tests**
> update for checkMessageProcessingErrors

- FlowCrypt/Common UI/CommonNodesInputs.swift
- FlowCrypt/Controllers/Setup/SetupInitialViewController.swift
- FlowCrypt/Extensions/UIColorExtensions.swift
- FlowCrypt/Functionality/Mail Provider/Imap/ImapError.swift
- FlowCrypt/Resources/en.lproj/Localizable.strings
This PR adds "use another account" button in case of error on `SetupInitialViewController`
close #1241
- Difficult to test (Do we have setup for UI tests for error flows?)
> Add use another account button to SetupInitialViewController

- FlowCrypt/Functionality/Services/GlobalRouter.swift
This PR shows activity indicator after tap on gmail login
close #447
> Add loading indicator for gmail sign in

- FlowCrypt.xcodeproj/project.pbxproj
- FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift
- FlowCrypt/Controllers/Setup/SetupCreatePassphraseAbstractViewController.swift
- FlowCrypt/Functionality/Mail Provider/Imap/ImapSessionProvider.swift
- FlowCrypt/Functionality/Mail Provider/Mail Sessions Providers/IMAPConnectionParameters.swift
- FlowCrypt/Functionality/Mail Provider/MailProvider.swift
- FlowCrypt/Functionality/Mail Provider/Threads/Imap+ThreadOperations.swift
This PR fix crash when open messages using IMAP provider
Conform IMAP to `MessagesThreadOperationsProvider` to prevent crash. 
Actual implementation should be done in scope of #1260
close #1145
> Fix crash when openning messages in IMAP

- FlowCrypt/Functionality/Services/GoogleUserService.swift
This PR adds `minExpiryDuration` parameter for fetching id tokens.
close #1222 
- Difficult to test (explain why) - tokens are fetched from Google API
> #1222 Add id tokens refresh on expiry

- FlowCrypt/Common UI/CommonNodesInputs.swift
This PR fixes layout for checkbox node
close #1273 
> Adopt CheckBoxTextNode to iPad

- Core/source/platform/xss.ts
- Core/source/test.ts
- Core/tooling/fix-bundles.js
- Core/webpack.bare.config.js
- FlowCrypt/Core/Core.swift
- FlowCrypt/Core/CoreHost.swift
This PR fixes errors when using `sanitize-html` through iOS `Core` functionality.
close #1285
- Does not need tests (refactor only, docs or internal changes) - we already have `testEndToEnd` test which fails when any error occurs during html sanitize.
> #1285 fix sanitize-html build

- FlowCrypt/Controllers/Inbox/InboxViewController.swift
This PR fixes inbox pagination after loading all messages/threads.
close #1284
- Difficult to test (explain why) - there is no easy way to calculate how many messages were loaded in appium, can be done in separate task if such test is needed.
> #1284 fix inbox pagination after loading all messages

- appium/tests/data/index.ts
- appium/tests/screenobjects/all-screens.ts
- appium/tests/screenobjects/email-provider.screen.ts
- appium/tests/screenobjects/menu-bar.screen.ts
- appium/tests/screenobjects/search.screen.ts
- appium/tests/screenobjects/setup-key.screen.ts
- appium/tests/screenobjects/splash.screen.ts
- appium/tests/specs/live/login/LoginToMultipleAccounts.spec.ts
This PR new spec for checking multiple accounts, added new methods for login to outlook accounts, updated login to gmail account,  added small fixes for scroll methods
close #484 
**Tests** 
> New spec for Multiple account

- appium/tests/helpers/PublicKeyHelper.ts
- appium/tests/screenobjects/contact-public-key.screen.ts
- appium/tests/screenobjects/contacts.screen.ts
- appium/tests/screenobjects/public-key-details.screen.ts
- appium/tests/specs/live/composeEmail/CheckRecipientColorAfterRemovingPubKey.spec.ts
This PR contains new spec for checking user color on compose email after removing pubkey for it, and checking pubkey after compose for contact with deleted pubkey
close #1353 
**Tests** _
> added new spec for checking user color after removing pubkey for it

- FlowCrypt/Controllers/Compose/ComposeViewController.swift
- FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
- FlowCrypt/Functionality/Mail Provider/MessagesList Provider/Model/MessageQuoteType.swift
- FlowCrypt/Resources/en.lproj/Localizable.strings
- FlowCryptUI/Cell Nodes/RecipientEmailNode.swift
- FlowCryptUI/Cell Nodes/RecipientEmailsCellNode.swift
- FlowCryptUI/Cell Nodes/RecipientEmailsCellNodeInput.swift
- Gemfile.lock
- appium/tests/data/index.ts
- appium/tests/helpers/DataHelper.ts
- appium/tests/screenobjects/email.screen.ts
- appium/tests/screenobjects/new-message.screen.ts
- appium/tests/specs/live/composeEmail/CheckComposeEmailAfterReopening.spec.ts
- appium/tests/specs/live/composeEmail/SendEmailToRecipientWithExpiredAndRevokedPublicKeys.spec.ts
- appium/tests/specs/live/composeEmail/SendEmailToRecipientWithoutPublicKey.spec.ts
- appium/tests/specs/live/composeEmail/SendEncryptedEmailAfterPassPhraseSessionEndedAndTrashIt.spec.ts
- appium/tests/specs/live/inbox/CheckReplyAndForwardForEncryptedEmail.spec.ts
- appium/tests/specs/mock/setup/UpdateOlderPubKeyToNewer.spec.ts
This PR adds `reply all` action on messages screen
close #953
- Tests added or updated - updated `CheckReplyAndForwardForEncryptedEmail` test to check `reply all` functionality
> #953 Add 'reply all' functionality

- FlowCrypt/Controllers/Inbox/InboxViewController.swift
- appium/tests/helpers/MailFolderHelper.ts
- appium/tests/helpers/TouchHelper.ts
- appium/tests/screenobjects/mail-folder.screen.ts
- appium/tests/specs/live/inbox/CheckinboxPaginationAfterLoadingAllEmails.spec.ts
This PR contains tests for checking inbox pagination after loading all messages
covered this case:
1. open Inbox screen
2. check number of messages (should be 20)
3. scroll to the bottom to load next page
4. check number of messages (should be more than 20)
5. scroll to the top of the list and perform pull-to-refresh
6. check number of messages (should be 20)
7. scroll to the bottom to load next page
8. check number of messages (should be more than 20)
close #1288 
issue #1366 
**Tests** 
> added new spec for checking inbox pagination after loading all messages

- FlowCrypt/Controllers/Inbox/InboxRenderable.swift
- FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
- FlowCrypt/Functionality/Mail Provider/Backup Provider/Gmail+Backup.swift
- FlowCrypt/Functionality/Mail Provider/Backup Provider/Imap+Backup.swift
- FlowCrypt/Functionality/Mail Provider/Gmail/GmailServiceError.swift
- FlowCrypt/Functionality/Mail Provider/Imap/ImapError.swift
- FlowCrypt/Functionality/Mail Provider/Message Provider/Gmail+Message.swift
- FlowCrypt/Functionality/Mail Provider/MessageOperations Provider/Gmail+MessageOperations.swift
- FlowCrypt/Functionality/Mail Provider/MessageOperations Provider/Imap+MessageOperations.swift
- FlowCrypt/Functionality/Mail Provider/Threads/MessagesThreadOperationsProvider.swift
- FlowCrypt/Functionality/Mail Provider/Threads/MessagesThreadProvider.swift
- FlowCrypt/Functionality/Services/Folders Services/RemoteFoldersProviderType/GmailService+folders.swift
- FlowCrypt/Functionality/Services/GoogleUserService.swift
- FlowCrypt/Resources/en.lproj/Localizable.strings
- FlowCryptAppTests/Functionality/Mail Provider/GmailServiceTest.swift
> Use missing instead of missed in variable/type names

- FlowCryptAppTests/Core/FlowCryptCoreTests.swift
> Create unit tests for composeEmail with signing key

- FlowCrypt/Controllers/Compose/ComposeViewController.swift
- FlowCrypt/Controllers/Compose/ComposeViewControllerInput.swift
- FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
This PR fixed cc recipients not respected issue when user choose to `Reply All`.
close #1405 // if this PR closes an issue
> #1405 Fix cc recipients not respected issue

- FlowCrypt/Controllers/Inbox/InboxViewController.swift
This PR fixes infinite call to fetchAndRenderEmailsOnly issue for empty folders & inbox loads 2 pages issue.
close #1366 // if this PR closes an issue
> #1366 Infinite call to fetchAndRenderEmailsOnly issue for empty folders

- FlowCrypt/Controllers/Search/SearchViewController.swift
This PR fixed keyboard hides on search screen (when user pauses typing) issue.
close #451 // if this PR closes an issue
> #451 Fix keyboard hides on search screen issue

- FlowCrypt/AppDelegate.swift
This PR fixed realm decryption issue when prewarm mode
issue #1373 (edited by Tom)
- Difficult to test (This case is hard to reproduce and happens to a few users when app is in prewarm mode)
> #1373 Fix realm decryption issue when prewarm mode

- FlowCrypt/Controllers/Compose/ComposeViewController.swift
This PR uses local contact to display compose view recipient state if public key lookup failed.
close #853 // if this PR closes an issue
- Difficult to test (This issue needs offline status or server down status to be reproduced)
> #853 Use local contact if public key lookup failed

- FlowCrypt.xcodeproj/project.pbxproj
- FlowCrypt/Functionality/Error Handling/Task+Retry.swift
- FlowCrypt/Functionality/Mail Provider/Threads/MessagesThreadProvider.swift
- FlowCryptAppTests/Functionality/Mail Provider/GmailServiceTest.swift
This PR added retry logic for Task level and added this logic in get threads list and get thread info calls.
Default retry count is `3` and can be changed by passing `maxRetryCount` parameter.
close #1442 // if this PR closes an issue
- Difficult to test (not sure what & how to test)
> #1442 Added retry logic for get threads list and thread info

- Core/package-lock.json
- Core/source/test.ts
This PR disables tslint rule `no-unsafe-any` for tests.
close #1489 
> issue #1489 Disable no-unsafe-any for tests

- FlowCrypt/Controllers/Setup/SetupEKMKeyViewController.swift
- FlowCrypt/Functionality/Services/Client Configuration Service/ClientConfiguration.swift
- FlowCryptAppTests/Functionality/Services/Client Configuration Service/ClientConfigurationTests.swift
This PR saves pass phrase in memory when FORBID_STORING_PASS_PHRASE is set in EKM Setup
close #1513 // if this PR closes an issue
> #1513 enable EKM setup without FORBID_STORING_PASS_PHRASE

- FlowCrypt.xcodeproj/project.pbxproj
- FlowCrypt/Functionality/Services/Contacts Service/Models/PubKey.swift
- FlowCryptCommon/Extensions/OptionalExtensions.swift
This PR uses `ifNotNil` instead of `map` for optionals to avoid confusions for non-swifters.
close #593 // if this PR closes an issue
> #593 Use ifNotNil

- FlowCrypt/Functionality/Services/ApiCall.swift
- appium/tests/specs/mock/setup/SetupShowsMeaningfulErrorFromFES.spec.ts
This PR adds request URL to API error modal
close #1584
> #1584 Add request URL to error modal

- FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift
- FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift
- FlowCrypt/Functionality/Services/Local Contacts Service/LocalContactsProvider.swift
- FlowCryptAppTests/Mocks/LocalContactsProviderMock.swift
This PR updates recipient.lastUsed only when composing
close #1176 // if this PR closes an issue
> #1176 Update recipient.lastUsed only when composing

- FlowCrypt/Controllers/Threads/AlertsFactory.swift
This PR fixed pass phrase alert behavior
close #1657  // if this PR closes an issue
> #1657 Fix pass phrase alert behavior

- FlowCrypt/Controllers/Inbox/InboxViewController.swift
- appium/tests/specs/mock/inbox/CheckEmptyTrash.spec.ts
This PR fixes crash when going back from message screen in `Trash` folder
close #1872
> #1872 Fix crash on Trash screen

- FlowCrypt/Functionality/Api/Account Server Apis/EnterpriseServerApiHelper.swift
- appium/api-mocks/apis/fes/fes-endpoints.ts
This PR added `external-service` to expected service value in FES response
close #2048 // if this PR closes an issue
> #2048 Add external-service to expected service value in FES response

- FlowCrypt/Controllers/Compose/ComposeRecipientPopupViewController.swift
- FlowCrypt/Controllers/Compose/ComposeViewDecorator.swift
- FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+ActionHandling.swift
- FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Nodes.swift
- FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+RecipientInput.swift
- FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+RecipientPopup.swift
- FlowCrypt/Extensions/UIColorExtensions.swift
- FlowCryptUI/Cell Nodes/RecipientEmailNode.swift
- FlowCryptUI/Cell Nodes/RecipientEmailsCellNodeInput.swift
- FlowCryptUI/Nodes/TextFieldNode.swift
- appium/tests/screenobjects/new-message.screen.ts
- appium/tests/specs/mock/composeEmail/CheckRecipientPopup.spec.ts
This PR updated recipient selection color
close #418 // if this PR closes an issue
close #2304 // if this PR closes an issue
> #418 Updated recipient selection color

- FlowCrypt/Resources/en.lproj/Localizable.strings
- FlowCryptUI/Nodes/PassPhraseAlertNode.swift
This PR implemented passphrase popup dark mode support 
close #2306 // if this PR closes an issue
> #2306 Passphrase popup dark mode support

- FlowCrypt/App/GeneralConstants.swift
- FlowCrypt/Controllers/Threads/Extensions/ThreadDetailsDecorator.swift
- FlowCrypt/Functionality/Mail Provider/Message Provider/ProcessedMessage.swift
- FlowCrypt/Resources/en.lproj/Localizable.strings
- FlowCryptUI/Cell Nodes/ThreadMessageInfoCellNode.swift
- FlowCryptUI/Nodes/BadgeNode.swift
- appium/tests/screenobjects/email.screen.ts
- appium/tests/specs/mock/inbox/CheckAllEmailSignatureCases.spec.ts
This PR added multiline support to signature badge
close #1086 // if this PR closes an issue
> #1086 Added multiline support to signature badge

- FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+ErrorHandling.swift
- FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+TableView.swift
- FlowCrypt/Functionality/Services/Compose Message Helper/ComposeMessageContext.swift
- FlowCrypt/Functionality/Services/Compose Message Helper/ComposeMessageHelper.swift
- FlowCrypt/Resources/en.lproj/Localizable.strings
- appium/tests/data/index.ts
- appium/tests/helpers/ElementHelper.ts
- appium/tests/helpers/TouchHelper.ts
- appium/tests/screenobjects/attachment.screen.ts
- appium/tests/screenobjects/new-message.screen.ts
- appium/tests/specs/mock/composeEmail/CheckSignOnlyKey.spec.ts
- appium/tests/specs/mock/composeEmail/SendEmailToRecipientWithExpiredAndRevokedPublicKeys.spec.ts
- appium/tests/specs/mock/composeEmail/SendEmailToRecipientWithoutPublicKey.spec.ts
This PR added ability to message recipient without valid public key
close #2421 // if this PR closes an issue
https://github.com/FlowCrypt/flowcrypt-ios/assets/77344191/ad6eacc7-b451-485b-9cb8-ef6a549d4d78
> #2421 feat: added ability to message recipient without valid public key

- .semaphore/semaphore.yml
- FlowCrypt/App/AppDelegate.swift
- FlowCrypt/Controllers/Compose/ComposeViewController.swift
- FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+ErrorHandling.swift
- FlowCrypt/Controllers/Inbox/Container/InboxViewContainerController.swift
- FlowCrypt/Functionality/Services/EKMVcHelper.swift
- appium/tests/data/index.ts
- appium/tests/specs/mock/composeEmail/CheckEKMRefreshAfterComposeError.spec.ts
- appium/tests/specs/mock/setup/SetupOnlyRevokedKeyFromEKM.spec.ts
- appium/tsconfig.json
This PR improved handling of invalid keys on message compose(Refresh EKM keys for invalid keys on message screen)
close #2438 // if this PR closes an issue
> #2438 improve handling of invalid keys on message compose

- FlowCrypt.xcodeproj/project.pbxproj
- FlowCrypt/Controllers/Compose/ComposeViewController.swift
- FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Drafts.swift
- FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+ErrorHandling.swift
- FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+MessageSend.swift
- FlowCrypt/Controllers/Threads/Models/AlertsFactory.swift
- FlowCrypt/Functionality/DataManager/Encrypted Storage/EncryptedStorage.swift
- FlowCrypt/Functionality/Services/Client Configuration Provider/ClientConfiguration.swift
- FlowCrypt/Functionality/Services/Compose Message Helper/ComposeMessageError.swift
- FlowCrypt/Functionality/Services/Compose Message Helper/ComposeMessageHelper.swift
- FlowCrypt/Models/Common/RawClientConfiguration.swift
- FlowCrypt/Models/Realm Models/ClientConfigurationRealmObject.swift
- FlowCryptAppTests/Functionality/PGP/PasswordProtectedMsgTest.swift
- FlowCryptCommon/Extensions/StringExtensions.swift
- FlowCryptUI/Nodes/CoreAlertNode.swift
- FlowCryptUI/Nodes/CustomAlertNode.swift
- FlowCryptUI/Nodes/PassPhraseAlertNode.swift
- appium/api-mocks/lib/configuration-types.ts
- appium/tests/screenobjects/new-message.screen.ts
- appium/tests/specs/mock/composeEmail/CheckPasswordMessageCompliance.spec.ts
This PR implemented password protected message compliance
close #2644// if this PR closes an issue
> #2644 Password protected message compliance

- FlowCrypt/Controllers/Threads/ThreadDetailsViewController+TableView.swift
- FlowCryptCommon/Extensions/StringExtensions.swift
- FlowCryptUI/Cell Nodes/ThreadDetailWebNode.swift
This PR fixed formatting issue in reply message with attachment
close #2672 // if this PR closes an issue
> #2672 Fix: formatting issue in reply message with attachment

- FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Nodes.swift
This PR fixed duplicated signature after draft save issue
close #2675 // if this PR closes an issue
> #2675 Fix: duplicated signature after draft save issue
