FlowCrypt/flowcrypt-ios

.gitattributes

This should make it easier to work as a team when it comes to merging changes.

add merge=union for .xbproj

---

FlowCrypt/Storyboards/Base.lproj/Main.storyboard

issue #21 
This is a rebased version of #46

Issue 21 ipad rebased

---

FlowCrypt/Common/Imap.swift

issue #52 do not fetchMsgs with empty uid set

---

FlowCrypt/Controllers/SideMenu/MyMenuTableViewController.swift
FlowCrypt/Storyboards/Base.lproj/Main.storyboard

I removed bounce on scroll, because I think this looks better. Please check it, if you do not agree with me let me now, I will change it

Added selection for first item in menu after start

---

FlowCrypt/Common/Constants.swift
FlowCrypt/Common/Imap.swift
FlowCrypt/Controllers/Inbox/InboxViewController.swift
FlowCrypt/Controllers/Msg/MsgViewController.swift

#15 #17 
Code contributed by RomanKovalchuk2019 
* Changed folder naming
* All folder names is capitalized now
* Added toast for btn attach tap
* Removed capitalization
* Changed converter
* Added pull to refresh
* Changed number of loads
* Changed max number of messages
* Fixed unread status change on inbox
* Code refactoring

issue #15 #17 inbox refresh - squashed (#61)

---

FlowCrypt/Controllers/Recover/RecoverViewController.swift
FlowCrypt/Core/CoreTypes.swift
FlowCrypt/Model/KeyInfo.swift
FlowCryptTests/FlowCryptCoreTests.swift

issue 67 update core + check that imported key isFullyEncrypted

---

FlowCrypt/Common/Imap.swift

issue 30 retry imap connection drop

---

FlowCrypt/Common/Imap.swift
FlowCrypt/Controllers/Msg/MsgViewController.swift

issue 77 show toast when msg not found

---

FlowCrypt/Common/Services/MessageKindProvider.swift
FlowCrypt/Controllers/Inbox/InboxViewController.swift

https://github.com/FlowCrypt/flowcrypt-ios/issues/75

Disable opening messages over 5mb

---

FlowCrypt/Controllers/SignIn/SignInViewController.swift
FlowCrypt/Storyboards/Base.lproj/Main.storyboard

https://github.com/FlowCrypt/flowcrypt-ios/issues/72

Added links on front page

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Controllers/Inbox/InboxViewController.swift
FlowCrypt/Controllers/Msg/MailDestination.swift
FlowCrypt/Controllers/Msg/MsgViewController.swift
FlowCrypt/Controllers/SideMenu/SideMenuNavigationController.swift
FlowCrypt/Views/NavigationBarActionButton.swift

https://github.com/FlowCrypt/flowcrypt-ios/issues/68

Mark message as read after tap on back button

---

FlowCrypt/Common/Constants.swift
FlowCrypt/Common/Errors.swift
FlowCrypt/Common/Imap/Imap+backup.swift
FlowCrypt/Extensions/Extensions.swift

https://github.com/FlowCrypt/flowcrypt-ios/issues/54

Search backups in all folders

---

FlowCrypt/Common/AttesterApi.swift
FlowCrypt/Common/Errors.swift
FlowCrypt/Common/Imap/Imap.swift
FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Core/Core.swift
FlowCrypt/Extensions/PromiseExtension.swift
FlowCrypt/Extensions/URLSessionExtension.swift
FlowCrypt/Lib/Bignum/bignum.c

issue #93 fix sender without pgp + refactor compose with Promise/await

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Common/Constants.swift
FlowCrypt/Common/Errors.swift
FlowCrypt/Common/Imap/Imap+backup.swift
FlowCrypt/Common/Imap/Imap+session.swift
FlowCrypt/Common/Services/Logger.swift
FlowCrypt/Common/Services/UserService.swift
FlowCrypt/Controllers/Recover/RecoverViewController.swift
FlowCrypt/Controllers/SideMenu/Menu/Models/FolderViewModel.swift
FlowCrypt/Extensions/DataExtension.swift
FlowCrypt/Extensions/SequenceExtension.swift

Issue #95 recovery after logout bug

---

FlowCrypt/Common/Imap/Imap+retry.swift
FlowCrypt/Controllers/SideMenu/Menu/MyMenuTableViewController.swift

issue #103 Promise.then -> catch

---

FlowCrypt/Controllers/Inbox/Model/InboxCellNodeInput .swift

https://github.com/FlowCrypt/flowcrypt-ios/issues/105
**Mobile**
**Desktop**

changed name of sender to display name

---

FlowCrypt/Controllers/Inbox/InboxViewController.swift
FlowCrypt/Controllers/Msg/MsgViewController.swift
FlowCrypt/Extensions/UIViewControllerExtension.swift

https://github.com/FlowCrypt/flowcrypt-ios/issues/119

Fix issues in InboxViewController fetching

---

FlowCrypt/Common/Imap/Imap+folders.swift
FlowCrypt/Common/Imap/Imap+msg.swift
FlowCrypt/Controllers/Msg/MsgViewController.swift
FlowCrypt/Views/NavigationBarItemsView.swift

isseu #112 expunge msgs after delete

---

FlowCrypt/Common/MailDestination.swift
FlowCrypt/Controllers/Inbox/Nodes/InboxCellNode.swift
FlowCrypt/Controllers/Msg/MsgViewController.swift
FlowCrypt/Controllers/SideMenu/Menu/Models/FolderViewModel.swift
FlowCrypt/Controllers/SideMenu/Menu/Models/MenuHeaderViewModel.swift
FlowCrypt/Controllers/SideMenu/Menu/MyMenuViewController.swift
FlowCrypt/Controllers/SideMenu/Menu/Nodes/HeaderNode.swift
FlowCrypt/Controllers/SideMenu/Menu/Nodes/MenuNode.swift

close https://github.com/FlowCrypt/flowcrypt-ios/issues/131

UI Updates

---

FlowCrypt/Info.plist

https://github.com/FlowCrypt/flowcrypt-ios/issues/136

Disable dark mode support

---

FlowCrypt/Controllers/Setup/Helpers/SetupDecorator.swift
FlowCrypt/Controllers/Setup/SetupViewController.swift
FlowCrypt/Resources/en.lproj/Localizable.strings

Issue 143 reversed buttons

---

FlowCrypt/Info.plist

close https://github.com/FlowCrypt/flowcrypt-ios/issues/151

Add missing key in info.plist for opening files

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/ImportKey/EnterPassPhraseViewController.swift
FlowCrypt/Controllers/Setup/SetupViewController.swift
FlowCrypt/Views/Nodes/TableNode.swift
FlowCrypt/Views/Nodes/TextFieldCellNode.swift

Dismiss keyboard on return press and scroll drag

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Common/AppErr.swift
FlowCrypt/Controllers/Inbox/InboxViewController.swift
FlowCrypt/Controllers/SideMenu/Main/SideMenuNavigationController.swift
FlowCrypt/Controllers/SideMenu/Menu/MyMenuViewController.swift
FlowCrypt/Resources/en.lproj/Localizable.strings

https://github.com/FlowCrypt/flowcrypt-ios/issues/123

Handling connection error inside inbox and folders

---

FlowCrypt/Controllers/ImportKey/ImportKeyViewController.swift

close https://github.com/FlowCrypt/flowcrypt-ios/issues/142

Refined acceptable types for importing key

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Common/Services/DataManager.swift
FlowCrypt/Common/Services/Encrypted Storage/EncryptedStorage.swift
FlowCrypt/Common/Services/Encrypted Storage/KeyChainService.swift
FlowCrypt/Common/Services/Local Storage/LocalStorage.swift
FlowCrypt/Common/Services/Local Storage/LocalStorageTest.swift
FlowCrypt/FlowCrypt.entitlements
FlowCrypt/FlowCryptRelease.entitlements
FlowCrypt/FlowCryptTestFlight.entitlements

fix local db encryption + enable data protection complete

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Compose/Helpers/ComposeViewController+Setup.swift

issue #172 don't show toast when message not sent

---

FlowCrypt/Common/Imap/Imap+backup.swift

close #161 
Turns out the iOS app does not check backup file extension at all, which should be fine. I ended up just refactoring it a bit.

issue 161 refactored imap+backup

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Compose/Helpers/ComposeViewController+Setup.swift

close https://github.com/FlowCrypt/flowcrypt-ios/issues/203

Typo fix recipient 

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Controllers/Compose/ComposeDecorator.swift
FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Compose/ComposeViewControllerInput.swift
FlowCrypt/Controllers/Msg/MsgViewController.swift
FlowCrypt/Resources/en.lproj/Localizable.strings

close https://github.com/FlowCrypt/flowcrypt-ios/issues/146

Quote previous reply

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Compose/ComposeViewDecorator.swift
FlowCrypt/Controllers/ImportKey/Enter Pass Phrase/EnterPassPhraseViewController.swift
FlowCrypt/Controllers/ImportKey/Import Key/EnterPassPhraseViewDecorator.swift
FlowCrypt/Controllers/ImportKey/Import Key/ImportKeyViewController.swift
FlowCrypt/Controllers/Message List/MsgListViewConroller.swift
FlowCrypt/Controllers/Msg/MessageViewController.swift
FlowCrypt/Controllers/Msg/MessageViewDecorator.swift
FlowCrypt/Controllers/Msg/MsgViewController.swift
FlowCrypt/Controllers/Settings/KeySettings/Key Detail Info/KeyDetailInfoViewController.swift
FlowCrypt/Controllers/Settings/KeySettings/Key Detail Info/KeyDetailInfoViewDecorator.swift
FlowCrypt/Controllers/Settings/KeySettings/Key Details/KeyDetailViewController.swift
FlowCrypt/Controllers/Settings/KeySettings/Key Details/KeyDetailViewDecorator.swift
FlowCrypt/Controllers/Settings/KeySettings/Key List/KeySettingsViewController.swift
FlowCrypt/Controllers/Settings/KeySettings/Key List/KeySettingsViewDecorator.swift
FlowCrypt/Controllers/Settings/Settings List/SettingsViewController.swift
FlowCrypt/Controllers/Settings/Settings List/SettingsViewDecorator.swift
FlowCrypt/Controllers/Setup/SetupViewController.swift
FlowCrypt/Controllers/Setup/SetupViewDecorator.swift
FlowCrypt/Controllers/SideMenu/Menu/MyMenuViewController.swift
FlowCrypt/Functionality/DataManager/DataService.swift
FlowCrypt/Functionality/Imap/Imap.swift
FlowCrypt/Functionality/Services/AppStartup.swift
FlowCrypt/Functionality/Services/UserService.swift
FlowCrypt/Resources/Naming Convention.md

https://github.com/FlowCrypt/flowcrypt-ios/issues/165
Defined what is: 
- ViewController
- ViewControllerDecorator
- ViewControllerProvider
- Service
- DataManager
- Node

Naming convention

---

FlowCrypt/Functionality/Imap/Imap+backup.swift

https://github.com/FlowCrypt/flowcrypt-ios/issues/202

Attempt to identify and specify an error on backup request

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Common UI/View Controllers/SegmentedViewController.swift
FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/ImportKey/Enter Pass Phrase/EnterPassPhraseViewController.swift
FlowCrypt/Controllers/ImportKey/Import Key/ImportKeyViewController.swift
FlowCrypt/Controllers/Msg/MessageViewController.swift
FlowCrypt/Controllers/Search/SearchViewController.swift
FlowCrypt/Controllers/Settings/Contacts/Contacts List/ContactDetailViewController.swift
FlowCrypt/Controllers/Settings/Contacts/Contacts List/ContactsListViewController.swift
FlowCrypt/Controllers/Settings/KeySettings/Key Detail Info/KeyDetailInfoViewController.swift
FlowCrypt/Controllers/Settings/KeySettings/Key Details/KeyDetailViewController.swift
FlowCrypt/Controllers/Settings/KeySettings/Key List/KeySettingsViewController.swift
FlowCrypt/Controllers/Settings/KeySettings/Public Key/PublicKeyDetailViewController.swift
FlowCrypt/Controllers/Settings/Settings List/SettingsViewController.swift
FlowCrypt/Controllers/Setup/SetupViewController.swift
FlowCrypt/Controllers/SignIn Other/EmailProviderViewController.swift
FlowCrypt/Controllers/SignIn/SignInViewController.swift
FlowCryptUI/Cell Nodes/CellNode.swift
FlowCryptUI/Cell Nodes/InfoCellNode.swift
FlowCryptUI/Cell Nodes/SetupTitleNode.swift
FlowCryptUI/Cell Nodes/SwitchCellNode.swift
FlowCryptUI/Nodes/LinkButtonNode.swift
FlowCryptUI/Nodes/SignInDescriptionNode.swift
FlowCryptUI/Nodes/SignInImageNode.swift
FlowCryptUI/Nodes/SigninButtonNode.swift
FlowCryptUI/Nodes/TableNode.swift
FlowCryptUI/Nodes/TableViewController.swift
FlowCryptUIApplication/ViewController.swift
Podfile.lock

close #260 
- Fix background color for cell nodes
- Use TableNodeViewController to apply changes for dark/light theme switch

Fix background color for cells

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Functionality/Mail Provider/MessagesList Provider/Gmail+MessagesList.swift
FlowCryptCommon/Extensions/CalendarExtension.swift
FlowCryptCommon/Extensions/DateFormattingExtensions.swift
FlowCryptTests/ExtensionTests.swift

This PR fixes dates representation on inbox screen
close #326
**Tests** :
- Tests added for date formatting

Dates representation on inbox screen

---

FlowCrypt/Functionality/Services/AttesterApi.swift
FlowCrypt/Functionality/Services/Contacts Services/RemoteContactsProvider.swift
FlowCrypt/Functionality/WKDURLs/PubLookup.swift

This PR returns [KeyDetails] from AttesterApi
close #333  
**Tests** :

Returned keydetails from AttesterApi

---

FlowCrypt/Functionality/Services/WKDURLsApi.swift

This PR excludes email domains from requesting wkd, accurately handling errors
close #332 
**Tests** :

WKD errors handling

---

.github/workflows/check-for-emails.yml

I neglected to update this repo when I updated all the others. This caused the problem in https://github.com/FlowCrypt/flowcrypt-ios/issues/339.

Update and rename main.yml to check-for-emails.yml

---

FlowCrypt/Functionality/DataManager/DataService.swift
FlowCrypt/Functionality/DataManager/Encrypted Storage/EncryptedStorage.swift
FlowCrypt/Functionality/DataManager/UserAccountService.swift

This PR rename `isAnyKey` to `doesAnyKeyExist`
close #364 
**Tests**:

Rename isAnyKey to doesAnyKeyExist

---

FlowCryptCommon/Extensions/URLExtension.swift

This PR fixes schema replace in URL
close #370
**Tests** :
- Does not need tests.

After downloading file, take user to correct folder

---

.semaphore/semaphore.yml

This PR comments out secrets task

Temporary disable secrets task

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Controllers/Setup/SetupBackupsViewController.swift
FlowCrypt/Controllers/SideMenu/Main/SideMenuNavigationController.swift
FlowCrypt/Controllers/SideMenu/NavigationController/MainNavigationController.swift
FlowCrypt/Controllers/SideMenu/NavigationController/NavigationChildController.swift

This PR hide back button on SetupBackupsViewController.
Adds functionality to easily hide back button on view controller.
close #374
**Tests** :
- Difficult to test: UIViewController

Hide back button on SetupBackupsViewController

---

FlowCrypt/Controllers/SignIn/SignInViewController.swift

This PR removes debug code
close #396
**Tests**:

Remove debug code

---

FlowCrypt/Controllers/Inbox/Container/InboxViewContainerController.swift
FlowCrypt/Controllers/Settings/KeyLegal/LegalViewControllersProvider.swift
FlowCrypt/Controllers/Setup/SetupBackupsViewController.swift
FlowCrypt/Controllers/Setup/SetupManuallyEnterPassPhraseViewController.swift
FlowCrypt/Controllers/SetupImap/SetupImapViewController.swift
FlowCrypt/Models/OrganisationalRule.swift

This PR replaces assertions with fatal errors in ViewControllers and OrgRules in appropriate places;
issue #387
**Tests** :
- Does not need tests

Replace assertion failure with fatal error - View Controllers

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCryptUI/Views/NavigationBarItemsView.swift

This PR disables navigation buttons during message sending.
close #403
- Difficult to test. (UIViewController)

Disable send message button while sending

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift

This PR fixes evaluation for the recipients in case of reply
close #419 
**Tests** :
- Difficult to test (UIViewController)

Evaluate recipient in case of reply

---

FlowCrypt/Core/Models/PassPhraseObject.swift

This PR add primary key to pass phrase object to be able to update object in Realm
close #415 
**Tests**:
- Difficult to test. (Realm functionality)

Add primaryKey to PassPhraseObject

---

FlowCrypt/Controllers/Settings/KeySettings/Key List/KeySettingsViewController.swift
FlowCrypt/Controllers/Settings/Settings List/SettingsViewController.swift
FlowCrypt/Controllers/Setup/SetupManuallyEnterPassPhraseViewController.swift
FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift
FlowCrypt/Functionality/Services/Key Services/KeyService.swift

This PR fixes bug when pass phrase expired
For testing purposes timeout can be changed in `InMemoryPassPhraseStorage`
close #416 
**Tests** :
- Difficult to test. Time consuming

Fix openning message with expired pass phrase

---

docker-mailserver/config/dovecot.cf
docker-mailserver/docker-compose.yml

This PR added plain connection support for the test email server
issue #425 // if it doesn't close the issue yet

Updated dovecot.cf to be able to use non-SSL connection

---

FlowCrypt/Controllers/Settings/Settings List/SettingsViewController.swift

This PR fixes checking org rules for transition to Backups.
close #463
**Tests** :

Backups button not working

---

.github/workflows/check-for-emails.yml

This PR fixes occasional failures in the email check action.
close #480
- Tested on the repo https://github.com/FlowCrypt/issue947-src/

issue #480 Fix check for emails action

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Common UI/Refreshable.swift
FlowCrypt/Controllers/Inbox/InboxViewController.swift
FlowCrypt/Controllers/SideMenu/Menu/MyMenuViewController.swift
FlowCrypt/Functionality/Error Handling/AppErr.swift

This PR checks top controller of side menu before open it.
close #453 
**Tests**:

Side menu top controller update

---

FlowCrypt/Controllers/Inbox/InboxViewController.swift
FlowCrypt/Functionality/Error Handling/AppErr.swift
FlowCrypt/Functionality/Mail Provider/Gmail/GmailServiceError.swift
FlowCrypt/Resources/en.lproj/Localizable.strings
FlowCryptUITests/Resources/UITestHelper.swift

This PR adds GmailServiceError handling in InboxViewController;
issue #429  
**Tests** :

All Mail folder on Gmail not working - Errors handling

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift

This PR updates recipient section on email search success;
close #428
**Tests**:

Adding a recipient wipes message content and subject

---

Core/package-lock.json
Core/package.json

This PR updates `deploy` npm task to update iOS app resources.
close #527

issue #527 Update iOS resources in deploy

---

FlowCrypt/Controllers/Msg/AlertsFactory.swift

This PR renames "Save" button from passphrase prompt dialog to "Ok"
close #524 // if this PR closes an issue

issue #524 rename pass phrase prompt button

---

README.md

This PR updates ruby version in README.md to support the latest CocoaPods.
close #572
**Tests**:

issue #572 update ruby version in README.md

---

FlowCrypt/Controllers/Msg/MessageViewController.swift
FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift

Message service getMessage should be called getAndProcessMessage

---

README.md

This PR updates readme with ui test secret info
close #534
**Tests** :

Information about test secrets missing in readme

---

FlowCrypt/Extensions/URLSessionExtension.swift

This PR removes user's oauth token from app logs.
close #440
**Tests**:
- Does not need tests

issue #440 remove Authorization header from logs

---

FlowCrypt/Controllers/Inbox/InboxViewDecorator.swift
FlowCryptUI/Cell Nodes/TextCellNode.swift

This PR adds insets to text cell node
close #461
**Tests** :

issue 461 inbox empty state entering

---

FlowCrypt/Extensions/UIViewControllerExtensions.swift

This PR blocks user interaction until loader is hidden
close #604
**Tests** :

Issue 604 message can be edited while spinner is shown

---

FlowCrypt/Controllers/Setup/SetupGenerateKeyViewController.swift
FlowCrypt/Core/Core.swift
FlowCryptAppTests/Core/FlowCryptCoreTests.swift

Further async/await refactoring

---

FlowCrypt/Controllers/Inbox/InboxViewController.swift
FlowCrypt/Controllers/Search/SearchViewController.swift
FlowCrypt/Controllers/Settings/Backup/Backups Scene/BackupViewController.swift
FlowCrypt/Controllers/Setup/SetupInitialViewController.swift
FlowCrypt/Core/Core.swift
FlowCrypt/Functionality/Mail Provider/Backup Provider/BackupProvider.swift
FlowCrypt/Functionality/Mail Provider/Backup Provider/Gmail+Backup.swift
FlowCrypt/Functionality/Mail Provider/Backup Provider/Imap+Backup.swift
FlowCrypt/Functionality/Mail Provider/Message Gateway/GmailService+send.swift
FlowCrypt/Functionality/Mail Provider/Message Gateway/Imap+send.swift
FlowCrypt/Functionality/Mail Provider/Message Gateway/MessageGateway.swift
FlowCrypt/Functionality/Mail Provider/MessagesList Provider/Gmail+MessagesList.swift
FlowCrypt/Functionality/Mail Provider/MessagesList Provider/Imap+MessagesList.swift
FlowCrypt/Functionality/Mail Provider/MessagesList Provider/MessagesListProvider.swift
FlowCrypt/Functionality/Mail Provider/SearchMessage Provider/Gmail+Search.swift
FlowCrypt/Functionality/Mail Provider/SearchMessage Provider/Imap+Search.swift
FlowCrypt/Functionality/Mail Provider/SearchMessage Provider/MessageSearchProvider.swift
FlowCrypt/Functionality/Services/Backup Services/BackupService.swift
FlowCrypt/Functionality/Services/Backup Services/BackupServiceType.swift
FlowCryptAppTests/Functionality/Mail Provider/GmailServiceTest.swift

This reverts commit f7bb5f0b60ee1a4ef65ced5f6c16c5d7eff99911 because it's broken as per #706. Ref #404 #689

Revert "issue #404 Replace Promise and Future with async/await (#689)"

---

FlowCrypt/Extensions/URLSessionExtension.swift
FlowCryptCommon/Trace.swift

Time units are wrong in the API call logs

---

FlowCrypt/Functionality/Services/Account Server Services/EnterpriseServerApi.swift
FlowCrypt/Functionality/Services/ApiCall.swift
FlowCrypt/Functionality/Services/Remote Private Key Services/EmailKeyManagerApi.swift
FlowCrypt/Functionality/Services/Remote Pub Key Services/AttesterApi.swift
FlowCrypt/Functionality/Services/Remote Pub Key Services/WkdApi.swift

API error responses - code improvements

---

FlowCrypt/Functionality/Error Handling/KeyServiceErrorHandler.swift
FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift
FlowCrypt/Functionality/Services/Local Private Key Services/KeyService.swift
FlowCrypt/Resources/en.lproj/Localizable.strings

Clarify why did keys fail to load from storage

---

FlowCrypt/Extensions/URLSessionExtension.swift

Request time out should print shorter error

---

FlowCrypt/Controllers/Inbox/InboxViewController.swift

close #864
- Difficult to test (requires special timing)

Crash when showing request time out

---

FlowCrypt/Controllers/Compose/ComposeViewDecorator.swift
FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageAttachment.swift

This PR <what does it do and why?>
close #894 // if this PR closes an issue
issue #894  // if it doesn't close the issue yet

Fixed #894, compose message shows human readable file size

---

appium/tests/data/index.ts

This PR contains changes for index file
close #914
**Tests**

Changed index file, removed values from .env file

---

FlowCrypt/Controllers/Settings/Contacts/Contacts List/ContactsListViewController.swift
FlowCrypt/Functionality/Services/Local Pub Key Services/LocalContactsProvider.swift

close #910
- Tests will be added later (issue #...)

Crash when opening Contacts screen

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Extensions/Error+Extension.swift

This PR fixes error message text for Compose screen
issue #918
- Tests will be added later (issue #...) - #919 

issue #918 fix error message on Compose screen

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Common UI/AttachmentManager.swift
FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Inbox/InboxRenderable.swift
FlowCrypt/Controllers/Msg/MessageViewController.swift
FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
FlowCrypt/Functionality/FilesManager/FilesManager.swift

close #929
- Tests will be added later (issue #911)

Attachment is not displayed in encrypted email

---

FlowCrypt/Common UI/AttachmentManager.swift

Fix retain cycle in AttachmentManager class

---

FlowCrypt/Controllers/Setup/SetupGenerateKeyViewController.swift
FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
FlowCrypt/Extensions/UIViewControllerExtensions.swift
FlowCrypt/Functionality/Services/Remote Pub Key Services/AttesterApi.swift

Convert remaining AttesterApiType from Promise to async

---

FlowCrypt/Controllers/Msg/MessageViewController.swift
FlowCrypt/Controllers/Settings/KeySettings/Key List/KeySettingsViewController.swift
FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift

Address PR 852 feedback

---

appium/tests/screenobjects/contact-public-key.screen.ts
appium/tests/specs/composeEmail/SelectRecipientByName.spec.ts

This PR consist changes for issue 945, updated names of methods and selectors for Contact-public-key-screen
close #945
**Tests**

updated names for methods and selectors for Contact-public-key-screen

---

appium/tests/screenobjects/splash.screen.ts

This PR contains changes for login method for finishing google authentication
close #973 
**Tests** 

Added fixes for login method for google authentication

---

FlowCrypt/Extensions/URLSessionExtension.swift
FlowCrypt/Functionality/Services/Account Server Services/EnterpriseServerApi.swift
FlowCrypt/Functionality/Services/ApiCall.swift
FlowCrypt/Functionality/Services/Remote Private Key Services/EmailKeyManagerApi.swift
FlowCrypt/Functionality/Services/Remote Pub Key Services/AttesterApi.swift
FlowCrypt/Functionality/Services/Remote Pub Key Services/WkdApi.swift

Refactor usages of URLSession.call

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Setup/SetupGenerateKeyViewController.swift
FlowCrypt/Extensions/BigIntExtension.swift
FlowCrypt/Extensions/Error+Extension.swift
FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift
FlowCrypt/Functionality/Services/Local Pub Key Services/ContactsService.swift
FlowCrypt/Functionality/Services/Remote Pub Key Services/AttesterApi.swift
FlowCrypt/Functionality/Services/Remote Pub Key Services/PubLookup.swift
FlowCrypt/Functionality/Services/Remote Pub Key Services/WkdApi.swift
FlowCrypt/Functionality/Services/Remote Pub Key Services/WkdUrlConstructor.swift
FlowCryptAppTests/Functionality/Services/Key Services/PubLookupTest.swift

This PR parallelizes pubkey lookup to speed it up.
close #999
**Tests**:

issue 999 parallelize pubkey lookup

---

appium/tests/data/index.ts
appium/tests/screenobjects/new-message.screen.ts
appium/tests/specs/composeEmail/SentEmailToRecipientWithoutPublicKey.spec.ts

This PR contains test where checking error on sending email to recipient without public key
close #919 
**Tests** 

Added test for checking error when sent email to recipient without public key

---

FlowCryptUI/Cell Nodes/ContactKeyCellNode.swift
FlowCryptUI/Cell Nodes/ContactUserCellNode.swift
FlowCryptUI/Cell Nodes/ThreadMessageSenderCellNode.swift
FlowCryptUI/Nodes/AttachmentNode.swift
FlowCryptUI/Nodes/KeySettingCellNode.swift
appium/tests/screenobjects/contact-public-key.screen.ts
appium/tests/screenobjects/email.screen.ts
appium/tests/screenobjects/new-message.screen.ts
appium/tests/screenobjects/public-key.screen.ts

This PR contains ned Accessibility Ids for elements which using in autotests, updats for appium tests
close #944 
**Tests** 

added accessibility identifiers for elements, updated appium tests

---

FlowCrypt/Controllers/Setup/SetupBackupsViewController.swift
FlowCrypt/Functionality/Services/AppStartup.swift
FlowCrypt/Functionality/Services/GlobalRouter.swift

This PR ensures that bad pass phrases are handled well when recovering from inbox backups.
close #1019
**Tests**:
- ui tests will be added later - will file issue shortly

issue 1019 show alert on bad backup pp

---

appium/tests/screenobjects/all-screens.ts
appium/tests/screenobjects/setup-key.screen.ts
appium/tests/specs/composeEmail/CheckComposeEmailAfterReopening.spec.ts
appium/tests/specs/composeEmail/SelectRecipientByName.spec.ts
appium/tests/specs/composeEmail/SentEmailToRecipientWithoutPublicKey.spec.ts
appium/tests/specs/inbox/CheckEncryptedEmailAfterRestartApp.spec.ts
appium/tests/specs/inbox/CheckReplyForEncryptedEmail.spec.ts
appium/tests/specs/inbox/ReadAttachmentEmail.spec.ts
appium/tests/specs/inbox/ReadEmailAfterRestartApp.spec.ts
appium/tests/specs/inbox/ReadTextEmail.spec.ts
appium/tests/specs/login/GmailLogin.spec.ts
appium/tests/specs/settings/CheckSettingsForLoggedUser.spec.ts

This PR contains changes for CreateKeyScreen. It is renamed to SetupKeyScreen
close  #1028 
**Tests** 

changed CreateKeyScreen to SetupKeyScreen

---

appium/tests/specs/composeEmail/SentEmailToRecipientWithoutPublicKey.spec.ts

This PR updates ui test name and tries running ui tests to see if they work.
no issue ref

update ui test name

---

FlowCrypt/Controllers/Threads/AlertsFactory.swift
FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
appium/tests/screenobjects/email.screen.ts
appium/tests/specs/inbox/CheckEncryptedEmailAfterRestartApp.spec.ts
appium/tests/specs/inbox/CheckReplyForEncryptedEmail.spec.ts
appium/tests/specs/inbox/ReadAttachmentEmail.spec.ts

This PR removes one of nearly identical methods
close #1046
**Tests**:

issue 1046 remove duplicate code in AlertsFactory

---

appium/config/wdio.shared.conf.js
appium/package.json
appium/tests/specs/login/GmailLogin.spec.ts

Reverts FlowCrypt/flowcrypt-ios#1059 -  I merged it too early by accident, status doesn't pass.

Revert "added wdio-video-reporter for failed spec video recording"

---

appium/tests/helpers/TouchHelper.ts
appium/tests/screenobjects/sent.screen.ts
appium/tests/screenobjects/trash.screen.ts

…dinates, updated tests
This PR contains new scroll method for refreshing emails list, it works with coordinates 
close #1053 
**Tests** 

issue #1053 appium improve pull to refresh method

---

FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
FlowCrypt/Resources/en.lproj/Localizable.strings

This PR changes decrypting to processing during loading
close #1093
---------
-------------------------
**Tests** :

Update decrypting title

---

FlowCrypt/Functionality/Services/Remote Pub Key Services/AttesterApi.swift
appium/api-mocks/apis/attester/attester-endpoints.ts
appium/api-mocks/lib/configuration-types.ts
appium/config/wdio.mock.conf.js

This PR enables attester mock functionality.
no issue

enable attester api mock for appium

---

FlowCrypt/Controllers/Setup/SetupEKMKeyViewController.swift
FlowCrypt/Functionality/Services/Local Private Key Services/InMemoryPassPhraseStorage.swift
FlowCrypt/Functionality/Services/Local Private Key Services/KeyService.swift
FlowCrypt/Functionality/Services/Local Private Key Services/PassPhraseService.swift
appium/tests/specs/live/inbox/CheckMessageProcessingErrors.spec.ts

This PR fixes EKM setup with multiple keys
close #1146
- Tests added or updated - updated `CheckMessageProcessingErrors` test

#1146 Fix multiple keys EKM setup

---

FlowCrypt/Controllers/Compose/ComposeViewDecorator.swift
FlowCryptUI/Cell Nodes/RecipientEmailNode.swift
FlowCryptUI/Cell Nodes/RecipientEmailsCellNode.swift
FlowCryptUI/Cell Nodes/RecipientEmailsCellNodeInput.swift

This PR adds index-based accessibilityIds for recipient
close #1197 
issue #1199 
**Tests**:

Add index-based accessibilityIds for recipient

---

appium/tests/screenobjects/mail-folder.screen.ts
appium/tests/specs/live/inbox/CheckEncryptedEmailAfterRestartApp.spec.ts
appium/tests/specs/live/inbox/CheckMessageProcessingErrors.spec.ts
appium/tests/specs/live/inbox/CheckReplyAndForwardForEncryptedEmail.spec.ts
appium/tests/specs/live/inbox/ReadAttachmentEmail.spec.ts
appium/tests/specs/live/inbox/ReadEmailAfterRestartApp.spec.ts
appium/tests/specs/live/inbox/ReadKeyMismatchEmail.spec.ts
appium/tests/specs/live/inbox/ReadTextEmail.spec.ts

Switch to SearchScreen.searchAndClickEmailBySubjec

---

.semaphore/semaphore.yml
appium/config/wdio.live.conf.js
appium/config/wdio.mock.conf.js
appium/config/wdio.shared.conf.js
appium/package.json

This PR fixes UI tests processing on Semaphore and adds test reports
close #1215
close #1245

#1215 Semaphore config updates

---

FlowCrypt/Controllers/SetupImap/SetupImapViewController.swift
FlowCrypt/Functionality/Mail Provider/Imap/Imap+retry.swift
FlowCrypt/Functionality/Mail Provider/Imap/Imap+session.swift
FlowCrypt/Functionality/Mail Provider/Imap/Imap.swift
FlowCryptUI/Nodes/TextFieldNode.swift

This PR fixes nil in imap/smtp session for other email providers
Also fixed autocapitalization while entering email
close #1181
- Tests will be added later (issue #484 )

Fix for imap session

---

FlowCryptAppTests/ExtensionTests.swift

Fix unit test

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Common UI/AttachmentManager.swift
FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Settings/Contacts/Contacts List/ContactKeyDetailViewController.swift
FlowCrypt/Controllers/Settings/KeySettings/Key Details/KeyDetailViewController.swift
FlowCrypt/Controllers/Setup/SetupCreatePassphraseAbstractViewController.swift
FlowCrypt/Controllers/Threads/AlertsFactory.swift
FlowCrypt/Controllers/Threads/MessageActionsHandler.swift
FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
FlowCrypt/Functionality/Services/AppStartup.swift
FlowCrypt/Functionality/Services/Backup Services/BackupService.swift
FlowCryptCommon/Extensions/UIAlertControllerExtensions.swift
FlowCryptCommon/Extensions/UIPopoverPresentationControllerExtensions.swift
FlowCryptCommon/Extensions/UIViewControllerExtensions.swift
FlowCryptUI/Cell Nodes/ThreadMessageInfoCellNode.swift

This PR fixes crash when showing UIAlertController and UIActivityViewController
close #1269
------------------------
----------
- Does not need tests (UI changes) 

iPad - centred popover presentation style

---

FlowCrypt/Controllers/SideMenu/Menu/MyMenuViewController.swift
FlowCrypt/Controllers/SideMenu/Menu/MyMenuViewDecorator.swift
FlowCryptUI/Cell Nodes/InfoCellNode.swift

This PR adds aid for multiple accounts
close #1302
- added aids

Add aid for multiple accounts

---

FlowCrypt/Controllers/Settings/Contacts/Contacts List/ContactKeyDetailDecorator.swift
FlowCrypt/Controllers/Settings/Contacts/Contacts List/ContactKeyDetailViewController.swift
FlowCryptUI/Cell Nodes/LabelCellNode.swift

This PR adds aids to ContactKeyDetailViewController
close #1314
- Added aids

Add aid to ContactKeyDetailViewController

---

FlowCrypt/Controllers/SideMenu/Main/SideMenuNavigationController.swift

This PR fixes menu width on iPad
close #1282
------------------
iPad
iPhone
----------------
- Does not need tests (UI changes)

Fix menu width on iPad

---

FlowCrypt/App/AppContext.swift
FlowCrypt/Functionality/Mail Provider/MailProvider.swift
FlowCrypt/Functionality/Services/AppStartup.swift

MailServiceProviderFactory.services not on main thread

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCryptUI/Cell Nodes/RecipientEmailsCellNode.swift
FlowCryptUI/Nodes/MessageRecipientsNode.swift
FlowCryptUI/Views/LeftAlignedCollectionViewFlowLayout.swift

This PR fixes layout for recipients input
close #1315
- Does not need tests (ui changes)

Fix for collection view layout

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Compose/ComposeViewControllerInput.swift
FlowCrypt/Controllers/Compose/ComposeViewDecorator.swift
FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
appium/tests/screenobjects/new-message.screen.ts

This PR apply focus when forwardinf
close #1085
- Does not need tests (refactor only, docs or internal changes) 

Focus on recipients when forwarding

---

FlowCrypt/Controllers/Inbox/InboxProviders.swift
FlowCrypt/Controllers/Inbox/InboxViewController.swift
FlowCryptCommon/Extensions/CollectionExtensions.swift
FlowCryptCommon/Extensions/StyleExtensions.swift
FlowCryptCommon/Extensions/UIVIewExtensions.swift
FlowCryptUI/Cell Nodes/SetupTitleNode.swift
FlowCryptUI/Cell Nodes/TextViewCellNode.swift
FlowCryptUI/Resources/Helpers.swift
Podfile.lock

This PR fixes wrong messages order on Inbox screen
issue #1120
- Difficult to test (explain why) - messages list on test account can change in the future, so it's not possible to get exact date of the last inbox message

#1120 Fix inbox items order

---

Gemfile.lock
appium/tests/specs/live/login/LoginToMultipleAccounts.spec.ts

This PR temporary disables `user should be able login to multiple accounts` test
issue #1383

#1383 disable multiple accounts test

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
Podfile
Podfile.lock

This PR fix multiple taps on attachment
close #1343
- Does not need tests (UI changes)

Add spinner when tap on attachment

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Compose/ComposeViewDecorator.swift

This PR refactors ComposeViewController and moved layout logic to decorator.
close #1393

#1393 Move compose layouting code to a separate file

---

Core/source/core/pgp-key.ts

This PR fixes some hacks related to openpgp.js. This became possible with new version of the openpgp.js.
close #1377

issue #1377 Fix some hacks

---

FlowCrypt/Functionality/Services/AppStartup.swift

This PR adds logout button in retry dialog when error happens during app start.
close #1279 // if this PR closes an issue

#1279 Added logout button in retry dialog on startup error

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift

This PR fixed search contacts view display issue when search text is empty in ComposeViewController
close #1414 // if this PR closes an issue
- ~Does not need tests (refactor only, docs or internal changes)~ not worth testing
`

#1414 Fix search contacts view display issue when search text is empty

---

FlowCrypt/Functionality/DataManager/Encrypted Storage/KeyChainService.swift

This PR adds a last resort throw to ensure we don't attempt to get storage encryption key while protected data is not available.
close #1373 
- Difficult to test - hard to reproduce

issue 1373 throw on protected data not available

---

FlowCrypt/Controllers/SideMenu/Main/SideMenuNavigationController.swift

This PR fixed issue which user cannot close side menu.
close #417 // if this PR closes an issue

#417 Hide side bar button for InboxViewContainerController

---

FlowCrypt/Controllers/Settings/Contacts/Contacts List/ContactsListViewController.swift
FlowCryptUI/Cell Nodes/ContactCellNode.swift

This PR fixed delete issue in contacts screen.
close #1422 // if this PR closes an issue

#1422 Fix delete issue in contacts screen

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Resources/en.lproj/Localizable.strings
FlowCryptUI/Cell Nodes/TextFieldCellNode.swift
FlowCryptUI/Nodes/TextFieldNode.swift
appium/tests/data/index.ts
appium/tests/specs/live/composeEmail/CheckInvalidEmailRecipient.spec.ts

This PR checked invalid email recipient in compose view and prevent adding invalid emails.
close #1318  // if this PR closes an issue

#1318 Check invalid email recipient in compose view

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Inbox/InboxViewController.swift
FlowCrypt/Controllers/Settings/Backup/Backups Option Scene/BackupOptionsViewController.swift
FlowCrypt/Controllers/Settings/Backup/Backups Scene/BackupViewController.swift
FlowCrypt/Controllers/Settings/Backup/Backups Seleckt Key Scene/BackupSelectKeyViewController.swift
FlowCrypt/Controllers/Setup/SetupGenerateKeyViewController.swift
FlowCrypt/Controllers/Setup/SetupInitialViewController.swift

This PR removed private actors.
close #1119 // if this PR closes an issue

#1119 Remove private actors

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Inbox/InboxViewController.swift
FlowCrypt/Controllers/SideMenu/Menu/MyMenuViewController.swift
FlowCrypt/Functionality/Services/Folders Services/FoldersService.swift
FlowCrypt/Functionality/Services/Folders Services/Models/FolderViewModel.swift
FlowCrypt/Functionality/Services/Folders Services/RemoteFoldersProviderType/GmailService+folders.swift
FlowCrypt/Resources/en.lproj/Localizable.strings

This PR fixed side menu folder items capitalized + slow load issue.
close #995 // if this PR closes an issue

#995 Side menu folder items capitalized + slow load issue

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Functionality/Services/GoogleUserService.swift

This PR used google api client to fetch user info.
close #996 // if this PR closes an issue

#996 Use google api client to fetch user info

---

FlowCrypt/AppDelegate.swift
FlowCrypt/Common UI/View Controllers/SegmentedViewController.swift
FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Inbox/InboxViewController.swift
FlowCrypt/Controllers/Setup/SetupManuallyEnterPassPhraseViewController.swift
FlowCrypt/Controllers/SideMenu/Main/SideMenuNavigationController.swift
FlowCrypt/Functionality/DataManager/Encrypted Storage/EncryptedStorage.swift
FlowCrypt/Functionality/DataManager/Encrypted Storage/Version5SchemaMigration.swift
FlowCrypt/Functionality/DataManager/Encrypted Storage/Version6SchemaMigration.swift
FlowCrypt/Functionality/DataManager/Local Storage/LocalStorage.swift
FlowCrypt/Functionality/Mail Provider/Threads/MessagesThreadOperationsProvider.swift
FlowCrypt/Functionality/Mail Provider/Threads/MessagesThreadProvider.swift
FlowCrypt/Functionality/Services/Account Server Services/Models/MultipartDataRequest.swift
FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageContext.swift
FlowCrypt/Functionality/Services/Folders Services/LocalFoldersProvider.swift
FlowCrypt/Functionality/Services/Local Contacts Service/LocalContactsProvider.swift
FlowCrypt/Functionality/Services/Local Private Key Services/InMemoryPassPhraseStorage.swift
FlowCrypt/Models/Realm Models/RecipientRealmObject.swift
FlowCryptAppTests/Functionality/Services/ComposeMessageServiceTests.swift
FlowCryptAppTests/Functionality/Services/PassPhraseStorageTests/InMemoryPassPhraseStorageTest.swift
FlowCryptAppTests/ImapHelperTest.swift
FlowCryptCommon/Extensions/UIViewControllerExtensions.swift
FlowCryptCommon/Extensions/URLSessionExtensions.swift
FlowCryptUI/Cell Nodes/ThreadMessageInfoCellNode.swift
FlowCryptUI/Nodes/LinkButtonNode.swift
FlowCryptUI/Views/LeftAlignedCollectionViewFlowLayout.swift
FlowCryptUIApplication/ViewController.swift

This PR removed foreach in all codebase.
close #1172 // if this PR closes an issue

#1172 Completely remove foreach

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Controllers/Setup/SetupGenerateKeyViewController.swift
FlowCrypt/Controllers/Setup/SetupInitialViewController.swift
FlowCrypt/Functionality/Services/Account Server Services/EnterpriseServerApi.swift
FlowCrypt/Functionality/Services/IdTokenUtils.swift

This PR refactored getIdToken
close #1367 // if this PR closes an issue

#1367 Refactor getIdToken

---

FlowCryptAppTests/Functionality/Services/ComposeMessageServiceTests.swift

This PR fixed odd recipient test
close #1445 // if this PR closes an issue

#1445 Fix odd recipient test

---

Podfile.lock
appium/tests/screenobjects/setup-key.screen.ts
appium/tests/specs/mock/setup/SetupWithoutFesWhenFesReturnsError.spec.ts

This PR contains test for checking setup screen when mock FES returns 404
close #1209 
**Tests**

Added new test for checking setup screen when mock FES returns 404 error

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Functionality/Services/GoogleUserService+Contacts.swift
FlowCrypt/Functionality/Services/GoogleUserService.swift
FlowCryptAppTests/Functionality/Mail Provider/GmailServiceTest.swift

This PR refactored cloud contact provider and google user service.
close #1129 // if this PR closes an issue

#1129 Refactor cloud contact provider and google user service

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift
appium/tests/screenobjects/new-message.screen.ts
appium/tests/specs/live/composeEmail/CheckCaretForReplyAndForward.spec.ts

This PR focuses textfield for reply/forward in ComposeView
close #1453 // if this PR closes an issue

#1453 Focus textfield for reply/forward

---

.semaphore/semaphore.yml
FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Controllers/Compose/ComposeRecipientPopupViewController.swift
FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageContext.swift
FlowCrypt/Models/Common/Recipient.swift
FlowCrypt/Models/Common/RecipientBase.swift
FlowCrypt/Resources/en.lproj/Localizable.strings
FlowCryptUI/Cell Nodes/ComposeRecipientPopupNameNode.swift
FlowCryptUI/Cell Nodes/RecipientEmailNode.swift
FlowCryptUI/Cell Nodes/RecipientEmailsCellNode.swift
appium/tests/screenobjects/new-message.screen.ts
appium/tests/specs/live/composeEmail/CheckRecipientPopup.spec.ts

This PR changed way how recipients are displayed when user taps recipient
close #1455 // if this PR closes an issue

#1455 Display recipient info popup when user tap recipients

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageRecipient.swift
appium/tests/data/index.ts
appium/tests/helpers/PublicKeyHelper.ts
appium/tests/specs/live/composeEmail/CheckComposeEmailAfterReopening.spec.ts
appium/tests/specs/live/composeEmail/CheckRecipientColorAfterRemovingPubKey.spec.ts
appium/tests/specs/live/composeEmail/CheckRecipientPopup.spec.ts
appium/tests/specs/live/composeEmail/RecipientListLabelCheck.spec.ts
appium/tests/specs/live/composeEmail/SelectRecipientByName.spec.ts
appium/tests/specs/live/composeEmail/SendEmailToRecipientWithExpiredAndRevokedPublicKeys.spec.ts
appium/tests/specs/live/composeEmail/SendEncryptedEmailAfterPassPhraseSessionEndedAndTrashIt.spec.ts
appium/tests/specs/live/inbox/CheckReplyAndForwardForEncryptedEmail.spec.ts
appium/tests/specs/live/settings/CheckRemovingContacts.spec.ts
appium/tests/specs/mock/setup/CheckRecipientsInOfflineMode.spec.ts
appium/tests/specs/mock/setup/FindEmailOnAttester.spec.ts
appium/tests/specs/mock/setup/RespectsDisallowAttesterSearchForDomainsOnPerDomainBasic.spec.ts
appium/tests/specs/mock/setup/UpdateOlderPubKeyToNewer.spec.ts

This PR used contact provider display name if it's set.
close #1473 // if this PR closes an issue
- Tests will be added later (issue #1471)

#1473 Use contact provider display name if it's set

---

.semaphore/semaphore.yml
FlowCrypt.xcworkspace/xcshareddata/swiftpm/Package.resolved
FlowCrypt/Controllers/Compose/ComposeRecipientPopupViewController.swift
FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+ActionHandling.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Nodes.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+RecipientInput.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+RecipientPopup.swift
FlowCryptUI/Cell Nodes/ComposeRecipientPopupNameNode.swift
appium/config/wdio.live.conf.js
appium/config/wdio.mock.conf.js
appium/tests/helpers/TouchHelper.ts
appium/tests/screenobjects/new-message.screen.ts
appium/tests/specs/live/composeEmail/CheckRecipientPopup.spec.ts
appium/tests/specs/mock/setup/CheckRecipientsInOfflineMode.spec.ts

This PR improved recipient popup and UI testing.
close #1471 // if this PR closes an issue

#1471 Improve recipient popup and UI testing

---

FlowCrypt/Controllers/Inbox/InboxViewController.swift

This PR fixed InboxViewController crash issue
close #1486 // if this PR closes an issue

#1486 Fix InboxViewController crash issue (from 0.8.2 crash log)

---

FlowCrypt.xcworkspace/xcshareddata/swiftpm/Package.resolved
FlowCrypt/Controllers/Compose/ComposeRecipientPopupViewController.swift
FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+ActionHandling.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Nodes.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+RecipientInput.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+RecipientPopup.swift
FlowCryptUI/Cell Nodes/ComposeRecipientPopupNameNode.swift
appium/config/wdio.live.conf.js
appium/config/wdio.mock.conf.js
appium/tests/helpers/ElementHelper.ts
appium/tests/helpers/TouchHelper.ts
appium/tests/screenobjects/email.screen.ts
appium/tests/screenobjects/new-message.screen.ts
appium/tests/screenobjects/old-version-app.screen.ts
appium/tests/specs/live/composeEmail/CheckRecipientPopup.spec.ts
appium/tests/specs/mock/setup/CheckRecipientsInOfflineMode.spec.ts

This PR contains 2 new methods for checking text and value in elements, The methods will wait 15 seconds until the text or value will present in element, after will return the error - "expected value/text to be different after 15s". When the text is appears before 15s, the methods will complete.
close #1448 
**Tests** 

Added new methods for checking Value and Text in tests using waitUntil

---

FlowCrypt/Functionality/Mail Provider/MessagesList Provider/Imap+MessagesList.swift

This PR contains 0.7.0 Crash fixes.
close #1485 // if this PR closes an issue

#1485 0.7.0 Crash fixes

---

FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Attachment.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Setup.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+TapActions.swift
appium/tests/helpers/TouchHelper.ts
appium/tests/screenobjects/new-message.screen.ts
appium/tests/specs/live/composeEmail/CheckRecipientEvaluationWhenTapAway.spec.ts

This PR triggers evaluation when user tap away from typed recipient address 
close #1468 // if this PR closes an issue

#1468 Trigger evaluation when user tap away from typed recipient address 

---

FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Nodes.swift

This PR fixed forward crash issue
close #1506 // if this PR closes an issue

#1506 Fix forward crash issue

---

FlowCrypt/Controllers/Bootstrap/InvalidStorageViewController.swift
FlowCrypt/Controllers/Settings/KeySettings/Key Details/KeyDetailViewController.swift
FlowCrypt/Controllers/Settings/KeySettings/Key Details/KeyDetailViewDecorator.swift
FlowCrypt/Controllers/Settings/KeySettings/Key List/KeySettingsViewController.swift
FlowCrypt/Functionality/DataManager/Encrypted Storage/EncryptedStorage.swift
FlowCrypt/Functionality/Services/GlobalRouter.swift
FlowCryptAppTests/Mocks/EncryptedStorageMock.swift
FlowCryptUI/Cell Nodes/RecipientEmailNode.swift
appium/tests/screenobjects/attachment.screen.ts
appium/tests/screenobjects/mail-folder.screen.ts
appium/tests/screenobjects/new-message.screen.ts
appium/tests/screenobjects/public-key-details.screen.ts
appium/tests/screenobjects/splash.screen.ts
appium/tests/specs/live/composeEmail/CheckComposeEmailAfterReopening.spec.ts
appium/tests/specs/live/inbox/ReadAttachmentEmail.spec.ts

This PR fixes storage reset on `InvalidStorageViewController`
close #1522
- Difficult to test (explain why) - difficult to reproduce "invalid storage" error

#1522 Fix “Reset storage” button

---

FlowCrypt/Controllers/SetupImap/SetupImapViewController.swift
FlowCrypt/Functionality/DataManager/SessionService.swift
FlowCrypt/Functionality/Mail Provider/Imap/Imap+retry.swift
FlowCrypt/Functionality/Mail Provider/Imap/Imap+session.swift
FlowCrypt/Functionality/Mail Provider/Imap/Imap.swift
FlowCrypt/Functionality/Mail Provider/Imap/ImapSessionProvider.swift
FlowCrypt/Functionality/Mail Provider/Mail Sessions Providers/IMAPConnectionParameters.swift
FlowCrypt/Functionality/Mail Provider/Mail Sessions Providers/SMTPSession.swift
FlowCrypt/Functionality/Mail Provider/Message Gateway/Imap+send.swift
FlowCrypt/Functionality/Mail Provider/UsersMailSession Provider/UserMailSessionProvider.swift
FlowCrypt/Functionality/Services/IdTokenUtils.swift

This PR fixed IMAP view crash.
close #1536 // if this PR closes an issue
- Difficult to test (Hard to reproduce this crash)

#1536 Fix IMAP view crash

---

FlowCrypt/Controllers/Inbox/InboxViewController.swift
appium/tests/helpers/MailFolderHelper.ts
appium/tests/screenobjects/mail-folder.screen.ts

This PR improved CheckInboxPaginationAfterLoadingAllEmails test
close #1537 // if this PR closes an issue

#1537 Improved CheckInboxPaginationAfterLoadingAllEmails test

---

FlowCrypt/Controllers/Settings/KeySettings/Key Details/KeyDetailViewController.swift
FlowCrypt/Controllers/Settings/KeySettings/Key Details/KeyDetailViewDecorator.swift
FlowCrypt/Controllers/Settings/KeySettings/Key List/KeySettingsViewController.swift
FlowCryptUI/Nodes/KeySettingCellNode.swift
appium/tests/screenobjects/keys.screen.ts

This PR used accessibility identifiers for keys screen
close #1545 // if this PR closes an issue

#1545 Use accessibility identifiers for keys screen

---

appium/tests/screenobjects/email.screen.ts
appium/tests/specs/live/composeEmail/CheckComposeEmailAfterReopening.spec.ts
appium/tests/specs/live/inbox/CheckReplyAndForwardForEncryptedEmail.spec.ts

This PR improved CheckReplyAndForwardForEncryptedEmail test
close #1567 // if this PR closes an issue

#1567 Improve CheckReplyAndForwardForEncryptedEmail test

---

FlowCrypt/Controllers/Inbox/InboxProviders.swift
FlowCrypt/Controllers/Inbox/InboxRenderable.swift
FlowCrypt/Functionality/Mail Provider/MessagesList Provider/MessagesListProvider.swift

This PR imprvoed context.folderPath nil/empty string.
close #1101 // if this PR closes an issue

#1101 context.folderPath nil/empty string improvements

---

appium/tests/specs/live/inbox/CheckMessageProcessingErrors.spec.ts

This PR fixed message processing error UI test.

Bugfix: fix message processing error ui test

---

appium/tests/helpers/ElementHelper.ts
appium/tests/helpers/TouchHelper.ts
appium/tests/screenobjects/email-provider.screen.ts
appium/tests/screenobjects/new-message.screen.ts
appium/tests/screenobjects/search.screen.ts
appium/tests/screenobjects/setup-key.screen.ts
appium/tests/screenobjects/splash.screen.ts

This PR uses clipboard for long input texts
close #1170 // if this PR closes an issue

#1170 Use clipboard for long input texts

---

FlowCrypt/Functionality/DataManager/Encrypted Storage/EncryptedStorage.swift
FlowCrypt/Functionality/DataManager/SessionService.swift
FlowCryptAppTests/Mocks/EncryptedStorageMock.swift

This PR renamed logout function in encrypted storage
close #1607 // if this PR closes an issue

#1607 Rename logout function in encrypted storage

---

FlowCrypt.xcworkspace/xcshareddata/swiftpm/Package.resolved
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Drafts.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+MessageSend.swift
FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageError.swift
FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift

This PR refactored missing pass phrase entry
close #1587 // if this PR closes an issue

#1587 Refactor missing pass phrase entry

---

appium/tests/specs/mock/setup/SetupRevokedAndValidKeysFromEKM.spec.ts

This PR added uuid to email subject when composing
close #1603 // if this PR closes an issue

#1603 Added uuid to email subject when composing

---

FlowCrypt/Models/Common/Keypair.swift
FlowCrypt/Models/Realm Models/KeypairRealmObject.swift

This PR fixed keypair duplicate logic
close #1589 // if this PR closes an issue

#1589 Fix Keypair duplicate logic

---

FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+ActionHandling.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+RecipientInput.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Setup.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+State.swift

This PR updated Compose Message updateState
close #1479 // if this PR closes an issue

#1479 Updated Compose Message updateState

---

.semaphore/semaphore.yml

This PR updates semaphoreci file, mostly to run a bit faster.
- due to the way semaphoreci runs these, when tasks are defined as many commands (lines), it runs slower than when it's defined in fewer commands (lines), even if the actual shell commands are the same. That means stringing shell commands with `&&` instead of new line actually makes it run faster, at times (sometimes there are delays going from line to line, and sometimes these delays can be long). On the other hand, putting everything on one line makes it messy and harder to debug when a command goes wrong, so I'm trying to strike a balance.
- I've changed the arrangement so that we only need two machines instead of one. Because our account has only 4 apple machines available, running on fewer machines will counter-intuitively …

issue 1488 update semaphoreci

---

FlowCrypt/Controllers/Setup/SetupBackupsViewController.swift
FlowCrypt/Controllers/Setup/SetupManuallyEnterPassPhraseViewController.swift
FlowCrypt/Core/Models/KeyAlgo.swift
FlowCrypt/Core/Models/KeyDetails.swift
FlowCrypt/Functionality/Services/Local Private Key Services/CombinedPassPhraseStorage.swift
FlowCryptAppTests/Core/CoreTypesTest.swift
FlowCryptAppTests/Core/Models/KeyDetailsTests.swift

This PR removed == operator for PassPhrase and KeyDetails
close #1547 // if this PR closes an issue

#1547 Remove == operator for PassPhrase and KeyDetails

---

FlowCrypt/Functionality/Services/Local Contacts Service/LocalContactsProvider.swift

This PR put db calls into a storage method
close #1171 // if this PR closes an issue

#1171 Put db calls into a storage method

---

Core/source/core/pgp-key.ts

Fix PgpKey.revoke()

---

FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
FlowCrypt/Functionality/Mail Provider/Gmail/GmailService.swift
FlowCrypt/Functionality/Mail Provider/MessagesList Provider/Model/Message.swift
FlowCrypt/Functionality/Mail Provider/Threads/MessagesThreadProvider.swift
appium/tests/data/index.ts
appium/tests/specs/live/inbox/CheckReplyForReplyToHeader.spec.ts

This PR honors reply-to header
close #1099 // if this PR closes an issue

#1099 Honor reply-to header

---

FlowCrypt/Functionality/Services/Local Private Key Services/CombinedPassPhraseStorage.swift
FlowCrypt/Functionality/Services/Local Private Key Services/InMemoryPassPhraseStorage.swift
FlowCryptAppTests/Functionality/Services/PassPhraseStorageTests/InMemoryPassPhraseStorageTest.swift

This PR fixed repeated prompts for pass phrase
close #1651 // if this PR closes an issue
- Difficult to test (Hard to reproduce)

#1651 Fix repeated prompts for pass phrase

---

FlowCrypt/Controllers/Inbox/InboxViewController.swift

This PR fix inbox reload issue when user wants to go back to Inbox view from ThreadDetailsViewController
close #1289 // if this PR closes an issue

#1289 Fix inbox reload issue

---

.gitignore
.husky/pre-commit
.semaphore/semaphore.yml
README.md
appium/.eslintrc.js
appium/package.json
appium/tsconfig.eslint.json
package-lock.json
package.json

This PR implemented commit hook and lint staged
close #1533 // if this PR closes an issue

#1533 Commit hook and lint staged

---

FlowCrypt/Controllers/Inbox/InboxRenderable.swift
FlowCrypt/Controllers/Inbox/InboxViewController.swift
FlowCrypt/Controllers/Threads/MessageThread.swift
FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift

This PR changed email read behavior
close #1660 // if this PR closes an issue

#1660 Change email/thread read behavior

---

FlowCrypt/Functionality/Api/Remote Pub Key Apis/PubLookup.swift
appium/tests/screenobjects/mail-folder.screen.ts
appium/tests/specs/mock/setup/CheckEmptyAllowAttesterSearchOnlyForDomains.spec.ts
appium/tests/specs/mock/setup/RespectsAllowAttesterSearchOnlyForDomains.spec.ts

This PR makes sure Attester lookup failure doesn't affect WKD in task group
close #1003 // if this PR closes an issue
- Difficult to test (Hard to reproduce)

#1003 make sure Attester lookup failure doesn't affect WKD in task group

---

.semaphore/semaphore.yml
appium/tests/specs/live/login/LoginToMultipleAccounts.spec.ts

This PR Simultaneously run ui tests in SemaphoreCI
close #1698 // if this PR closes an issue

#1698 Simultaneously run ui tests in SemaphoreCI

---

FlowCrypt/Functionality/Api/Account Server Apis/EnterpriseServerApi.swift

This PR fixed enterprise service upload issue for `send as`
close #1265 // if this PR closes an issue
- Difficult to test (Hard to reproduce)

#1265 Enterprise server upload fix

---

FlowCrypt/Controllers/Inbox/InboxViewController.swift

This PR fixed crash issue when user clicks no-result view
close #1716  // if this PR closes an issue

#1716 fix: crash issue when user clicks no-result view

---

FlowCrypt/App/AppContext.swift
appium/tests/specs/mock/setup/SetupShowsMeaningfulErrorFromFES.spec.ts

This PR fixed mid-setup show splash screen issue
close #1300 // if this PR closes an issue
- Tests will be added later (issue #1556)

#1300 Fix mid-setup show splash screen issue

---

FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift
FlowCrypt/Resources/en.lproj/Localizable.strings
FlowCryptCommon/Extensions/UIViewControllerExtensions.swift
appium/tests/data/index.ts
appium/tests/specs/mock/setup/CheckDecryptMessageWhenNoKeys.spec.ts

This PR fixed error message when no keys found
close #1726 // if this PR closes an issue

#1726 Proper error message when no keys found

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Controllers/Inbox/InboxViewController.swift
FlowCryptCommon/Extensions/UIViewControllerExtensions.swift
FlowCryptUI/Cell Nodes/EmptyFolderCellNode.swift
FlowCryptUI/Cell Nodes/EmptyFolerCellNode.swift
appium/api-mocks/apis/google/google-data.ts
appium/api-mocks/apis/google/google-endpoints.ts
appium/tests/screenobjects/base.screen.ts
appium/tests/screenobjects/mail-folder.screen.ts
appium/tests/specs/mock/inbox/CheckEmptyTrash.spec.ts

This PR added check empty trash ui test
close #1725 // if this PR closes an issue

#1725 Added check empty trash ui test

---

Core/source/core/common.ts
Core/source/core/mime.ts
Core/source/core/mnemonic.ts
Core/source/core/pgp-key.ts
Core/source/core/pgp-msg.ts
Core/source/entrypoint-bare.ts
Core/source/mobile-interface/endpoints.ts
Core/source/mobile-interface/format-output.ts
Core/source/mobile-interface/validate-input.ts
Core/source/platform/catch.ts
Core/source/platform/require.ts
Core/source/platform/util.ts
Core/source/test.ts
Core/source/test/test-utils.ts
appium/.eslintrc.js
appium/api-mocks/apis/google/google-endpoints.ts
appium/api-mocks/core/common.ts
appium/api-mocks/core/const.ts
appium/api-mocks/core/crypto/pgp/msg-util.ts
appium/api-mocks/core/crypto/pgp/openpgp-key.ts
appium/api-mocks/core/mime.ts
appium/api-mocks/core/types/openpgp.d.ts
appium/api-mocks/lib/api.ts
appium/api-mocks/lib/openpgp.d.ts
appium/api-mocks/platform/catch.ts
appium/api-mocks/platform/debug.ts
appium/api-mocks/platform/require.ts
appium/api-mocks/platform/store/contact-store.ts
appium/tests/screenobjects/email.screen.ts
appium/tests/types/node-forge.d.ts

This PR fixed any usage
close #1761 // if this PR closes an issue

#1761 Fix: any usage

---

.semaphore/semaphore.yml
fastlane/Fastfile

This PR builds app only once per ci workflow
close #1703 // if this PR closes an issue

#1703 build app only once per ci workflow

---

BuildTools/Package.resolved
BuildTools/Package.swift
Core/.eslintrc.js
Core/package.json
Core/source/mobile-interface/endpoints.ts
Core/source/mobile-interface/validate-input.ts
Core/tooling/fix-bundles.js
FlowCrypt/Core/Core.swift
FlowCryptAppTests/Core/FlowCryptCoreTests.swift

This PR adds `postbuild` phase for automatic `core` deploy on each build and also updates `rsa performance` tests on ios side (now it calculates average duration for multiple test runs for a more accurate results)
close #1788

#1788 openpgp improvements

---

Core/package.json
FlowCrypt.xcodeproj/project.pbxproj
README.md

This PR moves generated core js file to separate folder.
close #1854

#1854 Separate folder for generated js

---

FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+MessageSend.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Nodes.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+RecipientInput.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+TapActions.swift
appium/tests/screenobjects/new-message.screen.ts
appium/tests/specs/mock/composeEmail/CheckInvalidEmailRecipient.spec.ts

This PR fixes bug which allowed to send email with invalid recipient.
close #1878

#1878 Fix sending email with invalid recipient

---

.semaphore/semaphore.yml
Core/package-lock.json
Core/source/core/pgp-msg.ts
FlowCrypt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
appium/config/wdio.live.conf.js
appium/config/wdio.mock.conf.js
package-lock.json

This PR simplifies code for `openpgp` encrypt
close #1378

#1378 Fix openpgp types issue

---

Core/package-lock.json
FlowCrypt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Nodes.swift
FlowCrypt/Controllers/Threads/Extensions/ThreadDetailsDecorator.swift
FlowCrypt/Controllers/Threads/ThreadDetailsViewController+TableView.swift
FlowCrypt/Controllers/Threads/ThreadDetailsViewController+TapActions.swift
FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift
FlowCrypt/Functionality/Mail Provider/Message Provider/ProcessedMessage.swift
FlowCrypt/Functionality/Mail Provider/MessagesList Provider/Model/Message.swift
FlowCryptUI/Cell Nodes/MessageTextSubjectNode.swift
appium/package-lock.json
appium/tests/data/index.ts
appium/tests/helpers/ElementHelper.ts
appium/tests/screenobjects/email.screen.ts
appium/tests/screenobjects/new-message.screen.ts
appium/tests/specs/mock/composeEmail/CheckDraftsFunctionality.spec.ts
appium/tests/specs/mock/inbox/CheckThreadRendering.spec.ts
package-lock.json

This PR implements automatic hiding of quote text
close #1830

#1830 hide message quote

---

FlowCrypt.xcodeproj/project.pbxproj

This PR updates app version
close #1949

1.2.0: Drafts, performance, pgp/mime fix

---

appium/api-mocks/apis/google/google-endpoints.ts
appium/tests/specs/mock/composeEmail/CheckDraftsFunctionality.spec.ts

This PR fixed draft test
close #1930 // if this PR closes an issue

#1930 fix: draft test

---

README.md

This PR updated readme to include `swiftformat` installation process
close #2008 // if this PR closes an issue

#2008 feat: updated readme to include swiftformat installation

---

FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Nodes.swift

This PR fixed scroll issue in compose screen.
close #2007 // if this PR closes an issue
- Difficult to test (Couldn't test scrolling problem exactly in appium)

#2007 fix: scrolling not smooth on compose screen

---

FlowCryptUI/Cell Nodes/MessageTextSubjectNode.swift

This PR implemented feature which recognises links and make them tappable
close #2011 // if this PR closes an issue
- Difficult to test (It's hard to test such functionality with puppeteer)

#2011 feat: recognise links and make them tappable

---

FlowCrypt/App/AppContext.swift
FlowCrypt/App/GlobalRouter.swift
FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Contacts.swift
FlowCrypt/Functionality/Api/IdTokenUtils.swift
FlowCrypt/Functionality/Mail Provider/Gmail/GmailService.swift
FlowCrypt/Functionality/Mail Provider/MailProvider.swift
FlowCrypt/Functionality/Services/Google User Service/GoogleAuthManager.swift
FlowCryptAppTests/Core/FlowCryptCoreTests.swift
FlowCryptAppTests/Functionality/Mail Provider/GmailServiceTest.swift

This PR removed currentUserEmail from GoogleAuthManager
close #1992 // if this PR closes an issue

#1992 fix: Remove currentUserEmail from GoogleAuthManager

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Keyboard.swift
FlowCrypt/Controllers/Setup/SetupBackupsViewController.swift
FlowCrypt/Controllers/Setup/SetupCreatePassphraseAbstractViewController.swift
FlowCrypt/Controllers/Setup/SetupManuallyEnterPassPhraseViewController.swift
FlowCrypt/Controllers/SetupImap/SetupImapViewController.swift
FlowCryptUI/Nodes/TableViewController.swift

This PR unified keyboard notifications logic
close #1994 // if this PR closes an issue

#1994 feat: Unify keyboard notifications logic

---

FlowCrypt/Core/Core.swift

This PR fixed Javascript exception after app was in background for long time
close #2013 // if this PR closes an issue
- Difficult to test (Hard to reproduce in ci environment)

#2013 Fix: Javascript exception after app was in background for long time

---

FlowCrypt/Controllers/Compose/ComposeViewController.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Drafts.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Setup.swift
FlowCrypt/Functionality/Services/Compose Message Helper/ComposeMessageHelper.swift
FlowCryptCommon/Extensions/UIViewControllerExtensions.swift

This PR fixed draft error handlings.
close #2012 // if this PR closes an issue
- Difficult to test (Hard to reproduce in ci environment)

#2012 fix: Draft error handling

---

.semaphore/semaphore.yml
appium/config/wdio.live.conf.ts
appium/config/wdio.mock.conf.ts

This PR attempts to use Ubuntu (cheaper & more available instance) for TypeScript tests.

ubuntu instance for typescript test

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCryptAppTests/Core/FlowCryptCoreTests.swift

This PR updates app version
close #2088

1.2.2: Fix for encryption of forwarded attachments

---

FlowCrypt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
FlowCrypt/App/GeneralConstants.swift
FlowCrypt/Controllers/SideMenu/Menu/MyMenuViewController.swift
FlowCrypt/Functionality/Services/Folders Manager/RemoteFoldersApiClient/GmailService+folders.swift
appium/api-mocks/apis/google/google-data.ts
appium/tests/screenobjects/mail-folder.screen.ts

This PR fixed wrong order of user defined labels in side view
close #2160 // if this PR closes an issue

#2160 Order user defined labels in side view

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

This PR updated google libraries
close #2277 // if this PR closes an issue

#2277 Updated google libraries

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
FlowCrypt/Controllers/Compose/ComposeRecipientPopupViewController.swift
FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+TableView.swift
FlowCrypt/Controllers/SetupImap/SetupImapViewDecorator.swift
FlowCrypt/Controllers/Threads/ThreadDetailsViewController+TapActions.swift
FlowCrypt/Functionality/Mail Provider/MessagesList Provider/Imap+MessagesList.swift
FlowCrypt/Functionality/Mail Provider/MessagesList Provider/Model/MessageLabel.swift

This PR uses official SwiftLint
close #2278 // if this PR closes an issue

#2278 Use official SwiftLint

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt/Controllers/Setup/SetupCreatePassphraseAbstractViewController.swift
FlowCrypt/Controllers/Setup/SetupViewDecorator.swift
FlowCrypt/Resources/en.lproj/Localizable.strings
FlowCrypt/Resources/pass_phrase_hint.html

This PR added pass phrase hint modal
close #327 // if this PR closes an issue

#327 Added pass phrase hint

---

FlowCryptUI/Cell Nodes/InfoCellNode.swift

This PR fixed side menu folder label multi line issue
close #2322 // if this PR closes an issue

#2322 Side menu folder label multi line issue

---

FlowCrypt/Core/CoreTypes.swift
FlowCrypt/Functionality/Services/Compose Message Helper/ComposeMessageHelper.swift
FlowCryptAppTests/Core/CoreTypesTest.swift
appium/api-mocks/apis/fes/fes-endpoints.ts
appium/api-mocks/lib/api.ts
appium/api-mocks/lib/configuration-types.ts
appium/tests/specs/mock/composeEmail/CheckPasswordProtectedMessageBccLeak.spec.ts

This PR fixed blind carbon copy leak issue
close #2183 // if this PR closes an issue

#2183 Blind carbon copy leak fix

---

FlowCrypt/Controllers/Inbox/InboxViewController+TableView.swift
FlowCrypt/Controllers/Inbox/InboxViewController.swift

This PR reloads inbox view when index was not found.
close #2366 // if this PR closes an issue

#2366 Reload inbox view when index was not found

---

FlowCrypt/Controllers/Inbox/InboxItem.swift
FlowCrypt/Controllers/Inbox/InboxViewController+TableView.swift
FlowCrypt/Controllers/Threads/Extensions/MessageActionsHandler.swift

This PR shows `move to inbox` button for all cases when it's not inbox
close #2367 // if this PR closes an issue

#2367 Show `move to inbox` button for all cases when it's not inbox

---

FlowCrypt/App/AppDelegate.swift
FlowCrypt/Controllers/Inbox/Container/InboxViewContainerController.swift
FlowCrypt/Functionality/Services/EKMVcHelper.swift

This PR implemented feature to update keys from EKM 8 hours after last update time
close #2437 // if this PR closes an issue
- Difficult to test (Hard to test)

#2437 Feat: update keys from EKM 8 hours after last update time

---

FlowCryptCommon/Extensions/UIViewExtensions.swift

This PR fixed image crop issue on attachment preview screen
close #2456 // if this PR closes an issue

#2456 Fix: image crop issue on attachment preview screen

---

Core/source/assets/compat/mime-email-encrypted-inline-image.txt

This PR redacts the dev email that may not be expected in public source code.
close #2513 

#2513 Redact dev emails

---

FlowCrypt.xcodeproj/project.pbxproj
FlowCrypt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

This PR updated outdated swift packages
close #2674 // if this PR closes an issue

#2674 Update outdated swift packages
